/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QuadraticNumberFields.ClassGroup.GenusTheory.Discriminant
import QuadraticNumberFields.ClassGroup.Narrow.Ambiguous

/-!
# Ramified-Prime Boundary for Strict Two-Torsion

This file records the narrow item-11 target in a non-circular form. The actual
ambiguous class number formula is not imported from the archived genus file;
instead this file exposes the strict two-torsion cardinality target and the
ramified-prime generation interface that later ideal-arithmetic files must
prove.
-/

open scoped NumberField nonZeroDivisors

attribute [-instance] DivisionRing.toRatAlgebra

namespace QuadraticNumberFields
namespace ClassGroup
namespace Narrow

section Qsqrtd

variable (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]

local notation "OK" => 𝓞 (Qsqrtd (d : ℚ))

/-- The square subgroup of the strict/narrow class group of `ℚ(√d)`. -/
noncomputable abbrev strictSquareClassSubgroup :
    Subgroup (_root_.NarrowClassGroup OK) :=
  _root_.NarrowClassGroup.square OK

/-- The strict/narrow square-class quotient `Cl⁺ / Cl⁺²`. -/
abbrev strictSquareClassQuotient :=
  _root_.NarrowClassGroup.squareQuotient OK

/-- Strict genus formula target, written as the cardinality of `Cl⁺ / Cl⁺²`. -/
def strictGenusFormula : Prop :=
  Nat.card (strictSquareClassQuotient d) = 2 ^ (primeDiscriminantFactorCount d - 1)

/-- Emerton item 11 cardinality target, written as the cardinality of strict
two-torsion. -/
def strictTwoTorsionCardinality : Prop :=
  Nat.card (_root_.NarrowClassGroup.twoTorsion OK) =
    2 ^ (primeDiscriminantFactorCount d - 1)

/-- For finite strict class group, the strict genus formula is equivalent to
the strict two-torsion cardinality statement. -/
theorem strictGenusFormula_iff_strictTwoTorsionCardinality
    [Finite (_root_.NarrowClassGroup OK)] :
    strictGenusFormula d ↔ strictTwoTorsionCardinality d := by
  rw [strictGenusFormula, strictTwoTorsionCardinality, strictSquareClassQuotient,
    _root_.NarrowClassGroup.card_squareQuotient_eq_card_twoTorsion OK]

/-- Cardinality form of item 11 from the strict genus formula. -/
theorem card_twoTorsion_eq_of_strictGenusFormula
    [Finite (_root_.NarrowClassGroup OK)] (h : strictGenusFormula d) :
    Nat.card (_root_.NarrowClassGroup.twoTorsion OK) =
      2 ^ (primeDiscriminantFactorCount d - 1) :=
  (strictGenusFormula_iff_strictTwoTorsionCardinality d).mp h

/-- Inversion-fixed strict classes have the expected cardinality once the
strict genus formula is known. -/
theorem card_inversionFixedClass_eq_of_strictGenusFormula
    [Finite (_root_.NarrowClassGroup OK)] (h : strictGenusFormula d) :
    Nat.card (InversionFixedClass OK) = 2 ^ (primeDiscriminantFactorCount d - 1) := by
  rw [← card_twoTorsion_eq_card_inversionFixedClass OK]
  exact card_twoTorsion_eq_of_strictGenusFormula d h

/-- The index type for odd ramified rational primes in the current odd-prime
genus interface. In the odd-discriminant branch this has cardinality `t`. -/
abbrev RamifiedPrimeIndex :=
  {p : ℕ // p ∈ oddPrimeDiscriminantDivisors d}

/-- A proposed assignment of strict ideal classes to the ramified primes. The
later ideal-arithmetic layer should instantiate this using the prime ideals over
the ramified rational primes. -/
abbrev RamifiedPrimeStrictClassMap :=
  RamifiedPrimeIndex d → _root_.NarrowClassGroup OK

/-- The subgroup generated by the ramified-prime strict classes. -/
noncomputable def ramifiedPrimeStrictClassSpan
    (classes : RamifiedPrimeStrictClassMap d) :
    Subgroup (_root_.NarrowClassGroup OK) :=
  Subgroup.closure (Set.range classes)

/-- Emerton item 11 generation target: strict two-torsion is generated by the
strict classes of ramified primes. -/
def RamifiedPrimeStrictClassesGenerate : Prop :=
  ∃ classes : RamifiedPrimeStrictClassMap d,
    _root_.NarrowClassGroup.twoTorsion OK ≤ ramifiedPrimeStrictClassSpan d classes

/-- A convenient way to prove the ramified-prime generation target: every strict
two-torsion class is represented by one of the chosen ramified-prime classes. -/
theorem ramifiedPrimeStrictClassesGenerate_of_surjective
    (classes : RamifiedPrimeStrictClassMap d)
    (hsurj : ∀ C : _root_.NarrowClassGroup.twoTorsion OK,
      ∃ p : RamifiedPrimeIndex d, classes p = C) :
    RamifiedPrimeStrictClassesGenerate d := by
  refine ⟨classes, ?_⟩
  intro C hC
  obtain ⟨p, hp⟩ := hsurj ⟨C, hC⟩
  have hpC : classes p = C := by
    simpa using hp
  rw [← hpC]
  exact Subgroup.subset_closure ⟨p, rfl⟩

end Qsqrtd

end Narrow
end ClassGroup
end QuadraticNumberFields
