/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QNFMathlib.RingTheory.ClassGroup.Narrow
import QuadraticNumberFields.ClassGroup.Ambiguous.Basic
import QuadraticNumberFields.ClassGroup.Torsion
import QuadraticNumberFields.ClassGroup.RamifiedPrimes
import QuadraticNumberFields.Splitting.Qsqrtd.Factorization
import QuadraticNumberFields.Splitting.Qsqrtd.SqrtD

/-!
# Ramified-Prime Ideals for Strict Two-Torsion

Collects the ramified-prime ideals used in the narrow ambiguous-class argument.
If a rational prime `p` ramifies in `𝓞 K`, then the unique prime `P` above `p`
satisfies:

p ramified
⇒ (p) O K = P²
⇒ [P]⁺² = [(p)]⁺ = 1
⇒ [P]⁺ ∈ Cl⁺(K)[2]

-/

open scoped NumberField nonZeroDivisors
open scoped QuadraticNumberFields.Splitting

open Ideal FractionalIdeal

namespace QuadraticNumberFields
namespace ClassGroup
namespace Ambiguous

section Qsqrtd

variable (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]

local notation "OK" => 𝓞 (Qsqrtd (d : ℚ))

/-- A prime ideal over a ramified rational prime, obtained from the
ramification factorization. -/
noncomputable def ramifiedPrimeIdealOfIsRamified
    (p : ℕ) [Fact p.Prime] (hr : Ideal.IsRamifiedIn (𝔭(p)) OK) : Ideal OK :=
  (Splitting.exists_primeOver_map_eq_sq_of_isRamifiedIn d p hr).choose

/-- `ramifiedPrimeIdealOfIsRamified` lies over `(p)`. -/
theorem ramifiedPrimeIdealOfIsRamified_mem_primesOver
    (p : ℕ) [Fact p.Prime] (hr : Ideal.IsRamifiedIn (𝔭(p)) OK) :
    ramifiedPrimeIdealOfIsRamified d p hr ∈ Ideal.primesOver (𝔭(p)) OK :=
  (Splitting.exists_primeOver_map_eq_sq_of_isRamifiedIn d p hr).choose_spec.1

/-- The factorization `(p) = P²` for `ramifiedPrimeIdealOfIsRamified`. -/
theorem map_eq_sq_ramifiedPrimeIdealOfIsRamified
    (p : ℕ) [Fact p.Prime] (hr : Ideal.IsRamifiedIn (𝔭(p)) OK) :
    Ideal.map (algebraMap ℤ OK) (𝔭(p)) =
      ramifiedPrimeIdealOfIsRamified d p hr ^ 2 :=
  (Splitting.exists_primeOver_map_eq_sq_of_isRamifiedIn d p hr).choose_spec.2

/-- `ramifiedPrimeIdealOfIsRamified` is nonzero. -/
theorem ramifiedPrimeIdealOfIsRamified_ne_bot
    (p : ℕ) [Fact p.Prime] (hr : Ideal.IsRamifiedIn (𝔭(p)) OK) :
    ramifiedPrimeIdealOfIsRamified d p hr ≠ ⊥ := by
  have hpbot : 𝔭(p) ≠ (⊥ : Ideal ℤ) := by
    exact Splitting.pIdeal_ne_bot (Fact.out : Nat.Prime p)
  exact Ideal.ne_bot_of_mem_primesOver hpbot
    (ramifiedPrimeIdealOfIsRamified_mem_primesOver d p hr)

/-- The narrow class of `ramifiedPrimeIdealOfIsRamified`. -/
noncomputable def ramifiedPrimeNarrowClassOfIsRamified
    (p : ℕ) [Fact p.Prime] (hr : Ideal.IsRamifiedIn (𝔭(p)) OK) :
    NarrowClassGroup OK :=
  NarrowClassGroup.mk0
    ⟨ramifiedPrimeIdealOfIsRamified d p hr,
      mem_nonZeroDivisors_iff_ne_zero.mpr (ramifiedPrimeIdealOfIsRamified_ne_bot d p hr)⟩

/-- The principal ideal generated by a positive rational prime has trivial
narrow class. -/
theorem mk0_natCastSpanNonzeroIdeal_eq_one
    {p : ℕ} (hp : p.Prime) :
    NarrowClassGroup.mk0 (Splitting.natCastSpanNonzeroIdeal d p hp) =
      (1 : NarrowClassGroup OK) :=
  NarrowClassGroup.mk0_span_singleton_eq_one_of_isTotallyPositive
    (Splitting.natCast_ne_zero_ringOfIntegers d hp)
    (NarrowClassGroup.isTotallyPositive_natCast_fractionRing p hp.pos)

/-- The narrow class of a ramified prime ideal is two-torsion. -/
theorem ramifiedPrimeNarrowClassOfIsRamified_mem_twoTorsion
    (p : ℕ) [Fact p.Prime] (hr : Ideal.IsRamifiedIn (𝔭(p)) OK) :
    ramifiedPrimeNarrowClassOfIsRamified d p hr ∈
      NarrowClassGroup.twoTorsion OK := by
  rw [NarrowClassGroup.mem_twoTorsion_iff]
  let P0 : (Ideal OK)⁰ :=
    ⟨ramifiedPrimeIdealOfIsRamified d p hr,
      mem_nonZeroDivisors_iff_ne_zero.mpr (ramifiedPrimeIdealOfIsRamified_ne_bot d p hr)⟩
  have hspan : Ideal.map (algebraMap ℤ OK) (𝔭(p)) =
      Ideal.span ({(p : OK)} : Set OK) := by
    rw [Ideal.map_span, Set.image_singleton]
    rfl
  have hP0_sq : (P0 ^ 2 : (Ideal OK)⁰) =
      Splitting.natCastSpanNonzeroIdeal d p (Fact.out : Nat.Prime p) := by
    apply Subtype.ext
    exact (map_eq_sq_ramifiedPrimeIdealOfIsRamified d p hr).symm.trans hspan
  change (NarrowClassGroup.mk0 P0) ^ 2 = 1
  rw [← map_pow, hP0_sq]
  exact mk0_natCastSpanNonzeroIdeal_eq_one d (Fact.out : Nat.Prime p)

/-- The narrow class attached to a ramified-prime index. -/
noncomputable def ramifiedPrimeNarrowClass (p : RamifiedPrimeIndex d) :
    NarrowClassGroup OK := by
  classical
  letI : Fact p.1.Prime := ⟨prime_of_mem_ramifiedPrimeIndex d p⟩
  exact ramifiedPrimeNarrowClassOfIsRamified d p.1
    (isRamified_of_mem_ramifiedPrimeIndex d p)

/-- Each indexed ramified-prime narrow class is two-torsion. -/
theorem ramifiedPrimeNarrowClass_mem_twoTorsion (p : RamifiedPrimeIndex d) :
    ramifiedPrimeNarrowClass d p ∈ NarrowClassGroup.twoTorsion OK := by
  classical
  letI : Fact p.1.Prime := ⟨prime_of_mem_ramifiedPrimeIndex d p⟩
  simpa [ramifiedPrimeNarrowClass] using
    ramifiedPrimeNarrowClassOfIsRamified_mem_twoTorsion d p.1
      (isRamified_of_mem_ramifiedPrimeIndex d p)

/-- The prime ideal attached to a ramified-prime index. -/
noncomputable def ramifiedPrimeIdeal (p : RamifiedPrimeIndex d) : Ideal OK := by
  classical
  letI : Fact p.1.Prime := ⟨prime_of_mem_ramifiedPrimeIndex d p⟩
  exact ramifiedPrimeIdealOfIsRamified d p.1
    (isRamified_of_mem_ramifiedPrimeIndex d p)

/-- `ramifiedPrimeIdeal d p` lies over the rational prime indexed by `p`. -/
theorem ramifiedPrimeIdeal_mem_primesOver (p : RamifiedPrimeIndex d) :
    ramifiedPrimeIdeal d p ∈ Ideal.primesOver (𝔭(p.1)) OK := by
  classical
  letI : Fact p.1.Prime := ⟨prime_of_mem_ramifiedPrimeIndex d p⟩
  simpa [ramifiedPrimeIdeal] using
    ramifiedPrimeIdealOfIsRamified_mem_primesOver d p.1
      (isRamified_of_mem_ramifiedPrimeIndex d p)

/-- `ramifiedPrimeIdeal d p` is nonzero. -/
theorem ramifiedPrimeIdeal_ne_bot (p : RamifiedPrimeIndex d) :
    ramifiedPrimeIdeal d p ≠ ⊥ := by
  classical
  letI : Fact p.1.Prime := ⟨prime_of_mem_ramifiedPrimeIndex d p⟩
  simpa [ramifiedPrimeIdeal] using
    ramifiedPrimeIdealOfIsRamified_ne_bot d p.1
      (isRamified_of_mem_ramifiedPrimeIndex d p)

/-- `ramifiedPrimeIdeal d p` as a nonzero ideal. -/
noncomputable def ramifiedPrimeNonzeroIdeal
    (p : RamifiedPrimeIndex d) : (Ideal OK)⁰ :=
  ⟨ramifiedPrimeIdeal d p,
    mem_nonZeroDivisors_iff_ne_zero.mpr (ramifiedPrimeIdeal_ne_bot d p)⟩

/-- `ramifiedPrimeNonzeroIdeal` has narrow class `ramifiedPrimeNarrowClass`. -/
@[simp]
theorem mk0_ramifiedPrimeNonzeroIdeal (p : RamifiedPrimeIndex d) :
    NarrowClassGroup.mk0 (ramifiedPrimeNonzeroIdeal d p) =
      ramifiedPrimeNarrowClass d p := by
  classical
  letI : Fact p.1.Prime := ⟨prime_of_mem_ramifiedPrimeIndex d p⟩
  rfl

/-- The fiber above an indexed ramified discriminant prime is a singleton. -/
theorem primesOver_eq_singleton_ramifiedPrimeIdeal
    (p : RamifiedPrimeIndex d) :
    Ideal.primesOver (𝔭(p.1)) OK = {ramifiedPrimeIdeal d p} := by
  classical
  letI : Fact p.1.Prime := ⟨prime_of_mem_ramifiedPrimeIndex d p⟩
  have hpbot : 𝔭(p.1) ≠ (⊥ : Ideal ℤ) :=
    Splitting.pIdeal_ne_bot (prime_of_mem_ramifiedPrimeIndex d p)
  haveI : (𝔭(p.1)).IsMaximal := Splitting.pIdeal_isMaximal (prime_of_mem_ramifiedPrimeIndex d p)
  exact Ideal.primesOver_eq_singleton_of_isRamifiedIn
    (S := OK) (p := 𝔭(p.1)) (by norm_num : ringChar ℤ ≠ 2) hpbot
    (ramifiedPrimeIdeal_mem_primesOver d p)
    (isRamified_of_mem_ramifiedPrimeIndex d p)

/-- Different ramified-prime indices give different prime ideals. -/
theorem ramifiedPrimeIdeal_injective :
    Function.Injective (ramifiedPrimeIdeal d) := by
  intro p q hpq
  apply Subtype.ext
  have hp_under :=
    (ramifiedPrimeIdeal_mem_primesOver d p).2.1
  have hq_under :=
    (ramifiedPrimeIdeal_mem_primesOver d q).2.1
  have hspan : (𝔭(p.1) : Ideal ℤ) = 𝔭(q.1) := by
    rw [hp_under, hq_under, hpq]
  have hassoc : Associated (p.1 : ℤ) (q.1 : ℤ) :=
    Ideal.span_singleton_eq_span_singleton.mp hspan
  exact_mod_cast (Int.associated_iff_natAbs.mp hassoc)

/-- A normalized prime factor of an ideal lies over a ramified rational prime. -/
def normalizedFactorIsRamified
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)}) :
    Prop :=
  ∃ p : ℕ, p.Prime ∧
    P.1.comap (algebraMap ℤ OK) = 𝔭(p) ∧
    Ideal.IsRamifiedIn (𝔭(p)) OK

/-- A normalized factor of a nonzero ideal in the ring of integers is prime. -/
theorem normalizedFactor_isPrime
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)}) :
    P.1.IsPrime := by
  have hI0 : (I : Ideal OK) ≠ ⊥ := by
    simpa [Ideal.zero_eq_bot] using mem_nonZeroDivisors_iff_ne_zero.mp I.2
  exact (Ideal.mem_normalizedFactors_iff hI0).mp P.2 |>.1

/-- A normalized factor of a nonzero ideal in the ring of integers is nonzero. -/
theorem normalizedFactor_ne_bot
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)}) :
    P.1 ≠ ⊥ := by
  have hI0 : (I : Ideal OK) ≠ ⊥ := by
    simpa [Ideal.zero_eq_bot] using mem_nonZeroDivisors_iff_ne_zero.mp I.2
  have hPdata := (Ideal.mem_normalizedFactors_iff hI0).mp P.2
  intro hPbot
  exact hI0 (le_bot_iff.mp (by simpa [hPbot] using hPdata.2))

/-- A normalized factor whose comap is `(p)` lies over `(p)`. -/
theorem normalizedFactor_mem_primesOver_of_comap
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)})
    {p : ℕ} (hcomap : P.1.comap (algebraMap ℤ OK) = 𝔭(p)) :
    P.1 ∈ Ideal.primesOver (𝔭(p)) OK :=
  ⟨normalizedFactor_isPrime d P, ⟨hcomap.symm⟩⟩

/-- A ramified rational prime gives a ramified-prime index. -/
noncomputable def ramifiedPrimeIndexOfRamified
    {p : ℕ} (hp : p.Prime) (hram : Ideal.IsRamifiedIn (𝔭(p)) OK) :
    RamifiedPrimeIndex d := by
  refine ⟨p, ?_⟩
  exact (mem_ramifiedPrimes_iff_isRamifiedIn d p).mpr ⟨hp, hram⟩

/-- A normalized factor above a ramified rational prime is the corresponding
indexed ramified-prime ideal. -/
theorem normalizedFactor_eq_ramifiedPrimeIdeal_of_isRamifiedIn
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)})
    {p : ℕ} (hp : p.Prime)
    (hcomap : P.1.comap (algebraMap ℤ OK) = 𝔭(p))
    (hram : Ideal.IsRamifiedIn (𝔭(p)) OK) :
    ∃ hpRamified : RamifiedPrimeIndex d,
      P.1 = ramifiedPrimeIdeal d hpRamified := by
  let hpRamified := ramifiedPrimeIndexOfRamified d hp hram
  have hPover : P.1 ∈ Ideal.primesOver (𝔭(p)) OK :=
    normalizedFactor_mem_primesOver_of_comap d P hcomap
  have hsingleton :
      Ideal.primesOver (𝔭(p)) OK = {ramifiedPrimeIdeal d hpRamified} := by
    simpa [hpRamified] using
      primesOver_eq_singleton_ramifiedPrimeIdeal d hpRamified
  refine ⟨hpRamified, ?_⟩
  have hmem : P.1 ∈ ({ramifiedPrimeIdeal d hpRamified} : Set (Ideal OK)) := by
    simpa [hsingleton] using hPover
  simpa using hmem

/-- Being ramified is equivalent to being one of the indexed ramified-prime
ideals. -/
theorem normalizedFactorIsRamified_iff_exists_eq_ramifiedPrimeIdeal
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)}) :
    normalizedFactorIsRamified d P ↔
      ∃ p : RamifiedPrimeIndex d, P.1 = ramifiedPrimeIdeal d p := by
  constructor
  · rintro ⟨p, hp, hcomap, hram⟩
    exact normalizedFactor_eq_ramifiedPrimeIdeal_of_isRamifiedIn
      d P hp hcomap hram
  · rintro ⟨p, hP⟩
    refine ⟨p.1, prime_of_mem_ramifiedPrimeIndex d p, ?_, ?_⟩
    · rw [hP]
      exact (ramifiedPrimeIdeal_mem_primesOver d p).2.1.symm
    · exact isRamified_of_mem_ramifiedPrimeIndex d p

/-- The ramified-prime index attached to a normalized factor known to be
ramified. -/
noncomputable def ramifiedPrimeIndexOfNormalizedFactor
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)})
    (hP : normalizedFactorIsRamified d P) :
    RamifiedPrimeIndex d :=
  Classical.choose ((normalizedFactorIsRamified_iff_exists_eq_ramifiedPrimeIdeal
    d P).mp hP)

/-- A ramified normalized factor is the indexed ramified-prime ideal with the
same underlying rational prime. -/
theorem normalizedFactor_eq_ramifiedPrimeIdeal_ramifiedPrimeIndexOfNormalizedFactor
    {I : (Ideal OK)⁰}
    (P : {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (I : Ideal OK)})
    (hP : normalizedFactorIsRamified d P) :
    P.1 =
      ramifiedPrimeIdeal d
        (ramifiedPrimeIndexOfNormalizedFactor d P hP) :=
  Classical.choose_spec
    ((normalizedFactorIsRamified_iff_exists_eq_ramifiedPrimeIdeal
      d P).mp hP)

end Qsqrtd

end Ambiguous
end ClassGroup
end QuadraticNumberFields
