name = "QuadraticNumberFields"
version = "0.1.0"
keywords = ["math", "number-theory", "quadratic-fields"]
defaultTargets = ["QuadraticNumberFields"]
lintDriver = "runLinter"

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[require]]
name = "repl"
git = "https://github.com/leanprover-community/repl"
rev = "v4.30.0-rc2"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "QuadraticNumberFields"

[[lean_exe]]
name = "runLinter"
srcDir = "scripts"
supportInterpreter = true
