name = "QuadraticNumberFields"
version = "0.2.0"
keywords = ["math", "number-theory", "quadratic-fields"]
defaultTargets = [
  "QNFMathlib",
  "BinaryQuadraticForms",
  "QuadraticNumberFields",
  "FormClassGroup",
  "ImaginaryClassNumberOne",
  "Examples"
]
lintDriver = "runLinter"

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[require]]
name = "FiniteAbelianSmith"
git = "https://github.com/WangFrankie/FiniteAbelianSmith"

[[require]]
name = "repl"
git = "https://github.com/leanprover-community/repl"
rev = "v4.30.0-rc2"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "QNFMathlib"

[[lean_lib]]
name = "BinaryQuadraticForms"

[[lean_lib]]
name = "QuadraticNumberFields"

[[lean_lib]]
name = "FormClassGroup"

[[lean_lib]]
name = "ImaginaryClassNumberOne"

[[lean_lib]]
name = "Examples"

[[lean_exe]]
name = "runLinter"
srcDir = "scripts"
supportInterpreter = true
