/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QNFMathlib.RingTheory.Ideal.Span
import QuadraticNumberFields.Splitting.Qsqrtd.Monogenic

/-!
# The Integral Square Root `√d`

This file defines the element `√d` of `𝓞(ℚ(√d))` and proves the principal
ideal identity `(√d)² = (d)`.
-/

namespace QuadraticNumberFields
namespace Splitting

open scoped NumberField nonZeroDivisors QuadraticNumberFields.Splitting QuadraticAlgebra

variable (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]

/-- In `ℚ(√d)`, `omega` squares to `d`. -/
theorem omega_sq_eq_intCast :
    (QuadraticAlgebra.omega : Qsqrtd (d : ℚ)) ^ 2 =
      algebraMap ℤ (Qsqrtd (d : ℚ)) d := by
  rw [sq, QuadraticAlgebra.omega_mul_omega_eq_add]
  apply QuadraticAlgebra.ext <;> simp

/-- In `ℚ(√d)`, `omega` is integral over `ℤ`. -/
theorem omega_isIntegral :
    IsIntegral ℤ (QuadraticAlgebra.omega : Qsqrtd (d : ℚ)) := by
  refine ⟨Polynomial.X ^ 2 - Polynomial.C d,
    Polynomial.monic_X_pow_sub_C d (by norm_num), ?_⟩
  change (Polynomial.aeval (QuadraticAlgebra.omega : Qsqrtd (d : ℚ)))
      (Polynomial.X ^ 2 - Polynomial.C d) = 0
  simp [map_sub, map_pow, omega_sq_eq_intCast d]

/-- The integral square root `√d` as an element of `𝓞(ℚ(√d))`. -/
noncomputable def sqrtdInt : 𝓞(d) :=
  ⟨QuadraticAlgebra.omega, omega_isIntegral d⟩

@[simp]
theorem coe_sqrtdInt :
    (sqrtdInt d : Qsqrtd (d : ℚ)) = QuadraticAlgebra.omega :=
  rfl

/-- The integral square root `√d` is nonzero in `𝓞(ℚ(√d))`. -/
theorem sqrtdInt_ne_zero : sqrtdInt d ≠ 0 := by
  intro h
  have hcoe : ((sqrtdInt d : 𝓞(d)) : Qsqrtd (d : ℚ)) = 0 := by
    rw [h]
    simp
  rw [coe_sqrtdInt] at hcoe
  have him := congrArg QuadraticAlgebra.im hcoe
  norm_num at him

/-- The principal ideal `(√d)`, bundled as a nonzero integral ideal. -/
noncomputable def sqrtdSpanNonzeroIdeal : (Ideal (𝓞(d)))⁰ :=
  Ideal.spanSingletonNonzero (sqrtdInt_ne_zero d)

@[simp]
theorem coe_sqrtdSpanNonzeroIdeal :
    (sqrtdSpanNonzeroIdeal d : Ideal (𝓞(d))) =
      Ideal.span ({sqrtdInt d} : Set (𝓞(d))) :=
  rfl

/-- `√d` squares to `d` in `𝓞(ℚ(√d))`. -/
theorem sqrtdInt_sq :
    sqrtdInt d ^ 2 = algebraMap ℤ (𝓞(d)) d := by
  apply NumberField.RingOfIntegers.ext
  rw [NumberField.RingOfIntegers.coe_eq_algebraMap, map_pow]
  simp only [coe_sqrtdInt]
  rw [omega_sq_eq_intCast d]
  simp

/-- The principal ideal `(√d)` squares to the ideal `(d)`. -/
theorem span_sqrtdInt_sq :
    (Ideal.span {sqrtdInt d}) ^ 2 =
      Ideal.span {algebraMap ℤ (𝓞(d)) d} := by
  rw [Ideal.span_singleton_pow, sqrtdInt_sq]

/-- A rational prime remains nonzero in the ring of integers of `ℚ(√d)`. -/
theorem natCast_ne_zero_ringOfIntegers {p : ℕ} (hp : p.Prime) :
    (p : 𝓞(d)) ≠ 0 := by
  change algebraMap ℤ (𝓞(d)) (p : ℤ) ≠ 0
  exact (FaithfulSMul.algebraMap_injective ℤ (𝓞(d))).ne (by
    exact_mod_cast hp.ne_zero)

/-- The principal ideal generated by a rational prime in `𝓞(ℚ(√d))`, bundled as
a nonzero integral ideal. -/
def natCastSpanNonzeroIdeal (p : ℕ) (hp : p.Prime) : (Ideal (𝓞(d)))⁰ :=
  Ideal.spanSingletonNonzero (natCast_ne_zero_ringOfIntegers d hp)

@[simp]
theorem coe_natCastSpanNonzeroIdeal (p : ℕ) (hp : p.Prime) :
    (natCastSpanNonzeroIdeal d p hp : Ideal (𝓞(d))) =
      Ideal.span ({(p : 𝓞(d))} : Set (𝓞(d))) :=
  rfl

end Splitting
end QuadraticNumberFields
