/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import Mathlib.NumberTheory.Pell
import QuadraticNumberFields.ClassGroup.GenusTheory.AmbiguousIdeals.PositivePrincipal.Principal
import QuadraticNumberFields.ClassGroup.GenusTheory.AmbiguousIdeals.PositivePrincipal.Imaginary
import QuadraticNumberFields.ClassGroup.GenusTheory.AmbiguousIdeals.PositivePrincipal.Real

/-!
# Positive-Principal Ramified Parity Relation

This file assembles the positive-principal/sign-unit input needed for the unified
genus-theory ambiguous-ideal upper bound. The final consumer needs a nonzero
ramified parity vector whose full ramified parity ideal product is generated by a
totally positive element. The shared foundations live in `Internal`, and the
ordinary-principal, imaginary, and real branches are isolated in `Principal`,
`Imaginary`, and `Real`; this file only combines them into the final entry
`exists_nonzero_ramifiedParity_tp_generator`.
-/

namespace QuadraticNumberFields
namespace ClassGroup
namespace GenusTheory

open scoped nonZeroDivisors NumberField Pointwise QuadraticNumberFields.ClassGroup
open scoped QuadraticNumberFields.Splitting

attribute [-instance] DivisionRing.toRatAlgebra
attribute [local instance] FractionRing.liftAlgebra

namespace Internal

/-- Narrow positive-principal ramified parity relation.

This is the direct positive-principal/sign-unit input for the unified genus-theory proof.
In imaginary quadratic fields positivity is vacuous, as isolated in
`exists_nonzero_ramifiedParity_tp_generator_of_imaginary`; in real quadratic
fields this requires the genuine unit/sign correction. -/
theorem exists_nonzero_ramifiedParity_tp_generator
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)] :
    let R := NumberField.RingOfIntegers (Qsqrtd (d : ℚ))
    ∃ r : ({p // p ∈ ramifiedPrimes d} → Fin 2),
      (∃ p, r p ≠ 0) ∧
        ∃ γ : (FractionRing R)ˣ,
          NarrowClassGroup.IsTotallyPositive (γ : FractionRing R) ∧
            toPrincipalIdeal R (FractionRing R) γ =
              FractionalIdeal.mk0 (FractionRing R) (fullRamifiedParityIdealProduct d r) := by
  classical
  by_cases hd : d < 0
  · exact exists_nonzero_ramifiedParity_tp_generator_of_imaginary d hd
      (exists_nonzero_ramifiedParity_principal_generator d)
  · have hdpos : 0 < d := by
      have hdnonneg : 0 ≤ d := le_of_not_gt hd
      have hdne : d ≠ 0 := (Fact.out : Squarefree d).ne_zero
      exact lt_of_le_of_ne hdnonneg (Ne.symm hdne)
    exact exists_nonzero_ramifiedParity_tp_generator_of_real d hdpos
      (exists_nonzero_ramifiedParity_principal_generator d)

end Internal
end GenusTheory
end ClassGroup
end QuadraticNumberFields
