/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import Mathlib.NumberTheory.NumberField.ClassNumber
import Mathlib.RingTheory.Ideal.Norm.RelNorm
import QNFMathlib.NumberTheory.NumberField.Galois
import QuadraticNumberFields.ClassGroup.Torsion
import QuadraticNumberFields.ClassGroup.GenusTheory.Discriminant
import QuadraticNumberFields.QuadraticField.Conj
import QuadraticNumberFields.QuadraticField.RingOfIntegers
import QuadraticNumberFields.Splitting.Factorization

/-!
# Ambiguous Classes and the Genus-Theory Trunk `#Cl[2] = 2^{t-1}`

This file owns the load-bearing trunk of the genus theory of an imaginary
quadratic field `ℚ(√d)`: the *number of genera*

`#Cl[2] = 2 ^ (t - 1)`,

where `t = primeDiscriminantFactorCount d` is the number of rational primes
dividing the field discriminant. Everything in `GenusTheory/` previously reduced
the genus formula to an unproved surjectivity/bijectivity hypothesis on the odd
genus-character product `Φ`; this file replaces that conditional scaffolding by a
single honest statement and wires `genusFormula_of_mod_four_eq_one` to it.

## Mathematical content and proof boundary

The intended proof is the classical ambiguous class number formula, in its
cohomological form (Hilbert 90 + the periodic cohomology of the cyclic group
`G = Gal(ℚ(√d)/ℚ) = ⟨σ⟩`):

* the conjugation `σ` acts on `Cl` with `σ([I]) = [I]⁻¹` (since `I · σ(I) = (N I)`
  is principal), so the *ambiguous classes* `{C : σ C = C}` are exactly `Cl[2]`;
* `Ĥ⁰(G, I_K) = ⊕_{p ramified} ℤ/2 = (ℤ/2)^t` by cyclic periodicity, and
  `H¹(G, K^×) = 0` by Hilbert 90;
* the two short exact sequences `1 → O_K^× → K^× → P_K → 1` and
  `1 → P_K → I_K → Cl_K → 1` then give `#Cl^G = 2^{t-1}` (the imaginary-quadratic
  unit term is trivial: norms from `ℚ(√d)` are positive, so `-1` is not a norm).

Relative to class field theory this is the *genus fragment*: by reciprocity
`Cl/Cl² ≅ Gal(H_gen/K)` for the genus field `H_gen`, and the genus characters are
the characters of that Galois group. Because mathlib has no reciprocity law, we do
**not** take that shortcut; the ambiguous/cohomological route proves `#Cl[2]`
independently, staying inside Dedekind ring theory plus a thin slice of Galois
cohomology.

## Status

The prime-norm formula is available via
`Ideal.relNorm_eq_pow_of_isPrime_isGalois`; the local Galois-orbit calculation
identifying extension of the norm prime power with `P · σ(P)`, where
`σ = conjAutRingOfIntegers K`, is proved below from the degree-two splitting
trichotomy. The remaining proof boundary is the final ambiguous class number
formula, left as a visible `sorry` rather than hidden behind provider hypotheses.
-/

open scoped NumberField nonZeroDivisors Pointwise

namespace QuadraticNumberFields
namespace ClassGroup

attribute [-instance] DivisionRing.toRatAlgebra

/-! ## Ambiguous ideals

An ideal is *ambiguous* when it is fixed by a ring automorphism `σ`. For a
quadratic field `K = ℚ(√d)` the relevant `σ` is the nontrivial Galois
automorphism (conjugation `√d ↦ -√d`); the ambiguous ideals of `𝓞_K` are then the
conjugation-fixed ideals, generated by the rational ideals together with the
ramified primes. The σ-fixed *classes* are exactly `Cl[2]` (because
`σ([I]) = [I]⁻¹`), which is the bridge feeding the genus-theory trunk below.

Here we record the general predicate over an arbitrary ring automorphism;
specializing `σ` to the conjugation of `𝓞(Qsqrtd d)` is the next slice. -/

variable {B : Type*} [CommRing B]

/-- An ideal `I` of `B` is **ambiguous** with respect to a ring automorphism
`σ : B ≃+* B` when it is fixed by `σ`, i.e. `σ(I) = I`. -/
def IsAmbiguousIdeal (σ : B ≃+* B) (I : Ideal B) : Prop :=
  Ideal.map (σ : B →+* B) I = I

/-- Ambiguity of `I` is exactly fixedness of `I` under the pushforward `Ideal.map σ`. -/
theorem isAmbiguousIdeal_iff_isFixedPt (σ : B ≃+* B) (I : Ideal B) :
    IsAmbiguousIdeal σ I ↔ Function.IsFixedPt (Ideal.map (σ : B →+* B)) I :=
  Iff.rfl

/-- The whole ring is ambiguous. -/
theorem isAmbiguousIdeal_top (σ : B ≃+* B) : IsAmbiguousIdeal σ (⊤ : Ideal B) := by
  rw [IsAmbiguousIdeal, Ideal.map_top]

/-- The product of two ambiguous ideals is ambiguous. -/
theorem IsAmbiguousIdeal.mul {σ : B ≃+* B} {I J : Ideal B}
    (hI : IsAmbiguousIdeal σ I) (hJ : IsAmbiguousIdeal σ J) :
    IsAmbiguousIdeal σ (I * J) := by
  unfold IsAmbiguousIdeal at hI hJ ⊢
  rw [Ideal.map_mul, hI, hJ]

/-! ## Conjugation on the ring of integers

The relevant `σ` for a quadratic field `K` is its conjugation
`QuadraticField.conjAut K`, restricted to the ring of integers `𝓞 K`. We obtain
it from mathlib's `RingOfIntegers.mapRingEquiv`. The ambiguous ideals of `𝓞 K`
are then `IsAmbiguousIdeal (conjAutRingOfIntegers K)`. -/

/-- The conjugation of a quadratic field `K`, restricted to its ring of integers
`𝓞 K` as a ring automorphism. This is the `σ` whose fixed ideals are the
ambiguous ideals. -/
noncomputable def conjAutRingOfIntegers (K : Type*) [Field K] [Algebra ℚ K]
    [QuadraticField K] [QuadraticField.Conj K] : 𝓞 K ≃+* 𝓞 K :=
  NumberField.RingOfIntegers.mapRingEquiv (QuadraticField.conjAut K).toRingEquiv

@[simp]
theorem coe_conjAutRingOfIntegers_apply (K : Type*) [Field K] [Algebra ℚ K]
    [QuadraticField K] [QuadraticField.Conj K] (x : 𝓞 K) :
    (conjAutRingOfIntegers K x : K) = QuadraticField.conjAut K x := by
  rw [conjAutRingOfIntegers, NumberField.RingOfIntegers.mapRingEquiv_apply]
  rfl

/-- The conjugation of `𝓞 K`, regarded as a `ℤ`-algebra automorphism. -/
noncomputable def conjAutRingOfIntegersAlgEquiv (K : Type*) [Field K] [Algebra ℚ K]
    [QuadraticField K] [QuadraticField.Conj K] : 𝓞 K ≃ₐ[ℤ] 𝓞 K :=
  AlgEquiv.ofRingEquiv (f := conjAutRingOfIntegers K) (by
    intro n
    ext
    simp)

section ConjRestriction

variable {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
  [QuadraticField K] [QuadraticField.Conj K]

theorem galRestrict_conjAut_eq_conjAutRingOfIntegers :
    galRestrict ℤ ℚ K (𝓞 K) (QuadraticField.conjAut K) =
      conjAutRingOfIntegersAlgEquiv K := by
  ext x
  simpa [conjAutRingOfIntegersAlgEquiv, coe_conjAutRingOfIntegers_apply] using
    (algebraMap_galRestrict_apply (A := ℤ) (K := ℚ) (L := K) (B := 𝓞 K)
      (QuadraticField.conjAut K) x)

/-- The conjugation of the ring of integers is nontrivial. -/
theorem conjAutRingOfIntegersAlgEquiv_ne_refl :
    conjAutRingOfIntegersAlgEquiv K ≠ AlgEquiv.refl := by
  intro h
  apply QuadraticField.Conj.conj_ne_refl (K := K)
  apply (galRestrict ℤ ℚ K (𝓞 K)).injective
  rw [galRestrict_conjAut_eq_conjAutRingOfIntegers, h]
  change (1 : 𝓞 K ≃ₐ[ℤ] 𝓞 K) = (galRestrict ℤ ℚ K (𝓞 K)) (1 : Gal(K / ℚ))
  rw [map_one]

end ConjRestriction

/-! ## Conjugation acts as inversion on the class group

The bridge `σ([I]) = [I]⁻¹` follows from the principality of `I · σ(I)`: that
product is the extension to `𝓞 K` of the relative norm `relNorm ℤ (𝓞 K) I`, which
is principal because `ℤ` is a PID. Feeding this into `mk0_eq_mk0_inv_iff` shows
conjugation acts on `Cl` by inversion, so the σ-fixed (ambiguous) classes are
exactly `Cl[2]`. -/

section Bridge

variable {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
  [QuadraticField K] [QuadraticField.Conj K]

attribute [local instance] FractionRing.liftAlgebra

local instance : IsGalois (FractionRing ℤ) (FractionRing (𝓞 K)) := by
  haveI : IsGalois ℚ K := Algebra.IsQuadraticExtension.isGalois ℚ K
  exact NumberField.isGalois_fractionRing_ringOfIntegers K

omit [NumberField K] in
/-- The conjugate of a nonzero ideal is nonzero, since conjugation is bijective. -/
theorem map_conjAut_mem_nonZeroDivisors {I : Ideal (𝓞 K)}
    (hI : I ∈ nonZeroDivisors (Ideal (𝓞 K))) :
    Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) I ∈ nonZeroDivisors (Ideal (𝓞 K)) := by
  simp only [mem_nonZeroDivisors_iff_ne_zero, ne_eq, Ideal.zero_eq_bot,
    Ideal.map_eq_bot_iff_le_ker, RingHom.ker_coe_equiv, le_bot_iff] at hI ⊢
  exact hI

omit [QuadraticField.Conj K] in
/-- For a nonzero prime ideal `P` of `𝓞 K`, its relative ideal norm over `ℤ` is
the prime below `P`, raised to the inertia degree. This is the specialized form
of mathlib's Galois prime-norm formula needed for the ambiguous-product
identity. -/
theorem relNorm_eq_comap_pow_inertiaDeg_of_isPrime (P : Ideal (𝓞 K)) [P.IsPrime]
    (hP0 : P ≠ ⊥) :
    Ideal.relNorm ℤ P =
      (P.comap (algebraMap ℤ (𝓞 K))) ^ (P.comap (algebraMap ℤ (𝓞 K))).inertiaDeg P := by
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal inferInstance hP0
  haveI : (P.comap (algebraMap ℤ (𝓞 K))).IsMaximal :=
    Ideal.isMaximal_comap_of_isIntegral_of_isMaximal P
  exact Ideal.relNorm_eq_pow_of_isPrime_isGalois P (P.comap (algebraMap ℤ (𝓞 K)))

omit [QuadraticField.Conj K] in
/-- The fraction-field extension attached to the ring of integers of a quadratic
number field has degree two. -/
theorem finrank_fractionRing_ringOfIntegers_eq_two :
    Module.finrank (FractionRing ℤ) (FractionRing (𝓞 K)) = 2 := by
  haveI : Algebra.IsAlgebraic ℤ (𝓞 K) := Algebra.IsAlgebraic.of_finite ℤ (𝓞 K)
  calc
    Module.finrank (FractionRing ℤ) (FractionRing (𝓞 K)) = Module.finrank ℤ (𝓞 K) := by
      simpa using
        (Algebra.IsAlgebraic.finrank_of_isFractionRing (R := ℤ) (R' := FractionRing ℤ)
          (S := 𝓞 K) (S' := FractionRing (𝓞 K)))
    _ = Module.finrank ℚ K := by
      convert NumberField.RingOfIntegers.rank (K := K)
      exact Subsingleton.elim _ _
    _ = 2 := Algebra.IsQuadraticExtension.finrank_eq_two ℚ K

omit [QuadraticField.Conj K] in
/-- The Galois group of the fraction-field extension attached to `𝓞 K / ℤ` has
two elements. -/
theorem card_gal_fractionRing_ringOfIntegers_eq_two :
    Nat.card Gal(FractionRing (𝓞 K) / FractionRing ℤ) = 2 := by
  haveI : IsGalois ℚ K := Algebra.IsQuadraticExtension.isGalois ℚ K
  haveI : IsGalois (FractionRing ℤ) (FractionRing (𝓞 K)) :=
    NumberField.isGalois_fractionRing_ringOfIntegers K
  rw [IsGalois.card_aut_eq_finrank]
  exact finrank_fractionRing_ringOfIntegers_eq_two

omit [NumberField K] in
/-- The conjugate of a prime ideal lies over the same rational prime ideal. -/
theorem map_conjAut_liesOver_comap (P : Ideal (𝓞 K)) :
    (Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P).LiesOver
      (P.comap (algebraMap ℤ (𝓞 K))) := by
  letI : P.LiesOver (P.comap (algebraMap ℤ (𝓞 K))) := ⟨rfl⟩
  exact Ideal.LiesOver.of_eq_map_equiv (P.comap (algebraMap ℤ (𝓞 K)))
    (conjAutRingOfIntegersAlgEquiv K) rfl

omit [NumberField K] in
/-- The conjugate of a prime ideal is prime. -/
theorem map_conjAut_isPrime {P : Ideal (𝓞 K)} [P.IsPrime] :
    (Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P).IsPrime :=
  Ideal.map_isPrime_of_equiv (conjAutRingOfIntegers K)

omit [NumberField K] in
/-- The conjugate of a prime ideal is again one of the primes above the same
rational prime ideal. -/
theorem map_conjAut_mem_primesOver_comap (P : Ideal (𝓞 K)) [P.IsPrime] :
    Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P ∈
      Ideal.primesOver (P.comap (algebraMap ℤ (𝓞 K))) (𝓞 K) :=
  ⟨map_conjAut_isPrime, map_conjAut_liesOver_comap P⟩

/-- Prime-ideal form of the Galois-orbit calculation: extending the norm prime
power back to `𝓞 K` gives the product of `P` with its conjugate. -/
theorem map_comap_pow_inertiaDeg_eq_mul_map_conjAut_of_isPrime
    (P : Ideal (𝓞 K)) [P.IsPrime] (hP0 : P ≠ ⊥) :
    Ideal.map (algebraMap ℤ (𝓞 K))
        ((P.comap (algebraMap ℤ (𝓞 K))) ^
          (P.comap (algebraMap ℤ (𝓞 K))).inertiaDeg P) =
      P * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P := by
  let p : Ideal ℤ := P.comap (algebraMap ℤ (𝓞 K))
  haveI : P.IsMaximal := Ideal.IsPrime.isMaximal inferInstance hP0
  haveI : p.IsMaximal := by
    dsimp [p]
    exact Ideal.isMaximal_comap_of_isIntegral_of_isMaximal P
  have hp0 : p ≠ ⊥ := by
    dsimp [p]
    exact Ideal.IsIntegralClosure.comap_ne_bot K hP0
  have hPmem : P ∈ Ideal.primesOver p (𝓞 K) := by
    dsimp [p]
    exact ⟨inferInstance, ⟨rfl⟩⟩
  have hσmem :
      Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P ∈
        Ideal.primesOver p (𝓞 K) := by
    dsimp [p]
    exact map_conjAut_mem_primesOver_comap P
  have htri := Ideal.efg_trichotomy p (𝓞 K) (by norm_num : ringChar ℤ ≠ 2) hp0
  rcases htri with hsplit | hinert | hram
  · let σP : Ideal (𝓞 K) :=
      Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P
    have hσne : σP ≠ P := by
      -- Split case only: the nontrivial conjugation cannot lie in the
      -- decomposition group, whose cardinality is `e * f = 1`.
      intro hfix
      let τ : Gal(FractionRing (𝓞 K) / FractionRing ℤ) :=
        (galRestrict ℤ (FractionRing ℤ) (FractionRing (𝓞 K)) (𝓞 K)).symm
          (conjAutRingOfIntegersAlgEquiv K)
      letI := Ring.instAlgebraFractionRing
      letI := IsIntegralClosure.MulSemiringAction ℤ (FractionRing ℤ)
        (FractionRing (𝓞 K)) (𝓞 K)
      letI := Algebra.IsQuadraticExtension.isGaloisGroup
        (R := ℤ) (S := 𝓞 K) (by norm_num : ringChar ℤ ≠ 2)
      have hτne : τ ≠ 1 := by
        intro hτ
        apply conjAutRingOfIntegersAlgEquiv_ne_refl (K := K)
        have h := congrArg
          (galRestrict ℤ (FractionRing ℤ) (FractionRing (𝓞 K)) (𝓞 K)) hτ
        simpa [τ] using h
      have hτstab : τ ∈ MulAction.stabilizer
          Gal(FractionRing (𝓞 K) / FractionRing ℤ) P := by
        change τ • P = P
        change Ideal.map
          ((galRestrict ℤ (FractionRing ℤ) (FractionRing (𝓞 K)) (𝓞 K) τ :
            𝓞 K ≃ₐ[ℤ] 𝓞 K) : 𝓞 K →+* 𝓞 K) P = P
        dsimp [τ]
        rw [MulEquiv.apply_symm_apply]
        exact hfix
      have hcard_stab :
          Nat.card (MulAction.stabilizer Gal(FractionRing (𝓞 K) / FractionRing ℤ) P) = 1 := by
        haveI : P.LiesOver p := hPmem.2
        have horbit :
            MulAction.orbit Gal(FractionRing (𝓞 K) / FractionRing ℤ) P =
              Ideal.primesOver p (𝓞 K) := by
          exact Algebra.IsInvariant.orbit_eq_primesOver ℤ (𝓞 K)
            Gal(FractionRing (𝓞 K) / FractionRing ℤ) p P
        have horbit_card :
            Nat.card (MulAction.orbit Gal(FractionRing (𝓞 K) / FractionRing ℤ) P) = 2 := by
          rw [horbit]
          change (Ideal.primesOver p (𝓞 K)).ncard = 2
          simpa using hsplit.1
        have hprod :
            Nat.card (MulAction.orbit Gal(FractionRing (𝓞 K) / FractionRing ℤ) P) *
              Nat.card (MulAction.stabilizer Gal(FractionRing (𝓞 K) / FractionRing ℤ) P) =
                Nat.card Gal(FractionRing (𝓞 K) / FractionRing ℤ) := by
          simpa [Nat.card_prod] using
            Nat.card_congr
              (MulAction.orbitProdStabilizerEquivGroup
                Gal(FractionRing (𝓞 K) / FractionRing ℤ) P)
        rw [horbit_card, card_gal_fractionRing_ringOfIntegers_eq_two] at hprod
        omega
      have hsub :
          Subsingleton (MulAction.stabilizer Gal(FractionRing (𝓞 K) / FractionRing ℤ) P) :=
        (Nat.card_eq_one_iff_unique.mp hcard_stab).1
      have hτeq : τ = 1 := by
        have hsubeq :
            (⟨τ, hτstab⟩ :
              MulAction.stabilizer Gal(FractionRing (𝓞 K) / FractionRing ℤ) P) = 1 :=
          Subsingleton.elim _ _
        exact Subtype.ext_iff.mp hsubeq
      exact hτne hτeq
    have hfP : p.inertiaDeg P = 1 :=
      Ideal.inertiaDeg_eq_one_of_isSplitIn p (𝓞 K) (by norm_num : ringChar ℤ ≠ 2)
        (P' := P) ⟨hsplit.2.1, hsplit.2.2⟩
    have heP : p.ramificationIdx P = 1 := by
      letI := Ring.instAlgebraFractionRing
      letI := IsIntegralClosure.MulSemiringAction ℤ (FractionRing ℤ)
        (FractionRing (𝓞 K)) (𝓞 K)
      letI := Algebra.IsQuadraticExtension.isGaloisGroup
        (R := ℤ) (S := 𝓞 K) (by norm_num : ringChar ℤ ≠ 2)
      exact (Ideal.ramificationIdxIn_eq_ramificationIdx p P
        Gal(FractionRing (𝓞 K) / FractionRing ℤ)).symm.trans hsplit.2.1
    have heσP : p.ramificationIdx σP = 1 := by
      letI := Ring.instAlgebraFractionRing
      letI := IsIntegralClosure.MulSemiringAction ℤ (FractionRing ℤ)
        (FractionRing (𝓞 K)) (𝓞 K)
      letI := Algebra.IsQuadraticExtension.isGaloisGroup
        (R := ℤ) (S := 𝓞 K) (by norm_num : ringChar ℤ ≠ 2)
      haveI : σP.IsPrime := hσmem.1
      haveI : σP.LiesOver p := hσmem.2
      exact (Ideal.ramificationIdxIn_eq_ramificationIdx p σP
        Gal(FractionRing (𝓞 K) / FractionRing ℤ)).symm.trans hsplit.2.1
    have hset : Ideal.primesOver p (𝓞 K) = {P, σP} := by
      rw [Set.ncard_eq_two] at hsplit
      obtain ⟨P₁, P₂, hP₁P₂, hpair⟩ := hsplit.1
      have hP_or : P = P₁ ∨ P = P₂ := by
        rw [hpair] at hPmem
        simpa using hPmem
      have hσ_or : σP = P₁ ∨ σP = P₂ := by
        rw [hpair] at hσmem
        simpa [σP] using hσmem
      rcases hP_or with hP₁ | hP₂
      · rcases hσ_or with hσ₁ | hσ₂
        · exact (False.elim (hσne (hσ₁.trans hP₁.symm)))
        · rw [hpair, ← hP₁, ← hσ₂]
      · rcases hσ_or with hσ₁ | hσ₂
        · rw [hpair, ← hσ₁, ← hP₂, Set.pair_comm]
        · exact (False.elim (hσne (hσ₂.trans hP₂.symm)))
    have hmap : Ideal.map (algebraMap ℤ (𝓞 K)) p = P * σP := by
      have hfact := Ideal.map_algebraMap_eq_finset_prod_pow (R := 𝓞 K) (S := ℤ) hp0
      have hfin : (Ideal.primesOver p (𝓞 K)).toFinset = {P, σP} := by
        ext Q
        simp [hset]
      rw [hfin] at hfact
      simpa [σP, heP, heσP, hσne.symm] using hfact
    change Ideal.map (algebraMap ℤ (𝓞 K)) (p ^ p.inertiaDeg P) =
      P * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P
    rw [hfP, pow_one, hmap]
  · have hsingleton : Ideal.primesOver p (𝓞 K) = {P} := by
      rw [Set.ncard_eq_one] at hinert
      obtain ⟨Q, hQ⟩ := hinert.1
      have hPQ : P = Q := by
        rw [hQ] at hPmem
        exact hPmem
      rw [← hPQ] at hQ
      exact hQ
    have hσP : Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P = P := by
      rw [hsingleton] at hσmem
      exact hσmem
    have hfP : p.inertiaDeg P = 2 := by
      rw [← Ideal.inertiaDegIn_eq_inertiaDeg_of_primesOver_eq_singleton
        (p := p) (S := 𝓞 K) (P := P) hsingleton]
      exact hinert.2.2
    have hmap : Ideal.map (algebraMap ℤ (𝓞 K)) p = P := by
      have hfact := Ideal.map_algebraMap_eq_finset_prod_pow (R := 𝓞 K) (S := ℤ) hp0
      have heP : p.ramificationIdx P = 1 := by
        rw [← Ideal.ramificationIdxIn_eq_ramificationIdx_of_primesOver_eq_singleton
          (p := p) (S := 𝓞 K) (P := P) hsingleton]
        exact hinert.2.1
      have hfin : (Ideal.primesOver p (𝓞 K)).toFinset = {P} := by
        ext Q
        simp [hsingleton]
      rw [hfin] at hfact
      simpa [heP] using hfact
    change Ideal.map (algebraMap ℤ (𝓞 K)) (p ^ p.inertiaDeg P) =
      P * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P
    rw [hfP, Ideal.map_pow, hmap, hσP, pow_two]
  · have hsingleton : Ideal.primesOver p (𝓞 K) = {P} := by
      rw [Set.ncard_eq_one] at hram
      obtain ⟨Q, hQ⟩ := hram.1
      have hPQ : P = Q := by
        rw [hQ] at hPmem
        exact hPmem
      rw [← hPQ] at hQ
      exact hQ
    have hσP : Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P = P := by
      rw [hsingleton] at hσmem
      exact hσmem
    have hfP : p.inertiaDeg P = 1 := by
      rw [← Ideal.inertiaDegIn_eq_inertiaDeg_of_primesOver_eq_singleton
        (p := p) (S := 𝓞 K) (P := P) hsingleton]
      exact hram.2.2
    have hmap : Ideal.map (algebraMap ℤ (𝓞 K)) p = P ^ 2 := by
      have hfact := Ideal.map_algebraMap_eq_finset_prod_pow (R := 𝓞 K) (S := ℤ) hp0
      have heP : p.ramificationIdx P = 2 := by
        rw [← Ideal.ramificationIdxIn_eq_ramificationIdx_of_primesOver_eq_singleton
          (p := p) (S := 𝓞 K) (P := P) hsingleton]
        exact hram.2.1
      have hfin : (Ideal.primesOver p (𝓞 K)).toFinset = {P} := by
        ext Q
        simp [hsingleton]
      rw [hfin] at hfact
      simpa [heP] using hfact
    change Ideal.map (algebraMap ℤ (𝓞 K)) (p ^ p.inertiaDeg P) =
      P * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P
    rw [hfP, pow_one, hmap, hσP, pow_two]

/-- Prime-ideal case of the crux identity. This reduces the full
ambiguous-product identity to the Galois-orbit calculation on a single nonzero
prime ideal, plus the already-proved `⊥` case. -/
theorem mul_map_conjAut_eq_map_relNorm_of_isPrime (P : Ideal (𝓞 K)) [P.IsPrime] :
    P * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P =
      Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ P) := by
  by_cases hP0 : P = ⊥
  · simp [hP0, Ideal.relNorm_bot]
  · rw [relNorm_eq_comap_pow_inertiaDeg_of_isPrime P hP0,
      map_comap_pow_inertiaDeg_eq_mul_map_conjAut_of_isPrime P hP0]

/-- Multiplicative assembly of the ambiguous-product identity from the prime
ideal case. Both sides are multiplicative in `I`; this is the Dedekind-domain
factorization step that turns the prime-orbit calculation into the identity for
all ideals. -/
theorem mul_map_conjAut_eq_map_relNorm_of_prime_cases
    (hprime : ∀ P : Ideal (𝓞 K), P.IsPrime →
      P * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) P =
        Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ P))
    (I : Ideal (𝓞 K)) :
    I * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) I =
      Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ I) := by
  by_cases hI : I = ⊥
  · simp [hI, Ideal.relNorm_bot]
  rw [← Ideal.prod_normalizedFactors_eq_self hI]
  refine Multiset.prod_induction
      (fun J : Ideal (𝓞 K) =>
        J * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) J =
          Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ J)) _ ?_ ?_ ?_
  · intro J L hJ hL
    rw [Ideal.map_mul, map_mul, Ideal.map_mul]
    calc
      J * L * (Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) J *
          Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) L) =
          (J * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) J) *
            (L * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) L) := by
        ac_rfl
      _ = Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ J) *
          Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ L) := by
        rw [hJ, hL]
  · simp [Ideal.relNorm_top, Ideal.map_top]
  · intro Q hQ
    rw [Ideal.mem_normalizedFactors_iff hI] at hQ
    exact hprime Q hQ.1

/-- **Crux identity (boundary).** The product `I · σ(I)` of an ideal with its
conjugate equals the extension to `𝓞 K` of the relative norm `relNorm ℤ I`. This
is the ideal-level "product of Galois conjugates equals the relative norm". Mathlib
provides only the prime-case pieces (`relNorm_eq_pow_of_isPrime_isGalois`,
`relNorm_smul`, ...), so the multiplicative-on-primes assembly is left here. -/
theorem mul_map_conjAut_eq_map_relNorm (I : Ideal (𝓞 K)) :
    I * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) I =
      Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ I) := by
  refine mul_map_conjAut_eq_map_relNorm_of_prime_cases ?_ I
  intro P hP
  haveI : P.IsPrime := hP
  exact mul_map_conjAut_eq_map_relNorm_of_isPrime P

/-- **Product of an ideal with its conjugate is principal.** For a nonzero ideal
`I` of `𝓞 K`, the product `I · σ(I)` is a nonzero principal ideal: it is the
extension of `relNorm ℤ I`, which is principal because `ℤ` is a PID. -/
theorem exists_span_mul_map_conjAut {I : Ideal (𝓞 K)} (hI : I ≠ ⊥) :
    ∃ x : 𝓞 K, x ≠ 0 ∧
      I * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) I = Ideal.span {x} := by
  have hrel : Ideal.relNorm ℤ I ≠ ⊥ := by
    rw [ne_eq, ← Ideal.spanNorm_eq, Ideal.spanNorm_eq_bot_iff]; exact hI
  obtain ⟨n, hn⟩ := IsPrincipalIdealRing.principal (Ideal.relNorm ℤ I)
  rw [Ideal.submodule_span_eq] at hn
  have hn0 : n ≠ 0 := by
    rintro rfl
    exact hrel (by rw [hn, Ideal.span_singleton_eq_bot.mpr rfl])
  refine ⟨algebraMap ℤ (𝓞 K) n, ?_, ?_⟩
  · simpa only [map_zero] using (FaithfulSMul.algebraMap_injective ℤ (𝓞 K)).ne hn0
  · rw [mul_map_conjAut_eq_map_relNorm, hn, Ideal.map_span, Set.image_singleton]

/-- **σ([I]) = [I]⁻¹.** Conjugation acts on the ideal class group as inversion: the
class of the conjugate ideal is the inverse class. This is the bridge that turns
the ambiguous (σ-fixed) classes into the two-torsion subgroup `Cl[2]`. -/
theorem mk0_map_conjAut_eq_inv (I : (Ideal (𝓞 K))⁰) :
    ClassGroup.mk0 ⟨Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) (I : Ideal (𝓞 K)),
        map_conjAut_mem_nonZeroDivisors I.2⟩ = (ClassGroup.mk0 I)⁻¹ := by
  have hI : (I : Ideal (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.zero_eq_bot] using mem_nonZeroDivisors_iff_ne_zero.mp I.2
  rw [ClassGroup.mk0_eq_mk0_inv_iff]
  obtain ⟨x, hx0, hx⟩ := exists_span_mul_map_conjAut hI
  exact ⟨x, hx0, by rw [mul_comm]; exact hx⟩

end Bridge

/-! ## Genus-theory trunk -/

/-- The ideal classes fixed by inversion. For quadratic fields,
`mk0_map_conjAut_eq_inv` identifies conjugation-fixed classes with these
inversion-fixed classes, hence with `Cl[2]`. This is the result-side object used
by the genus-theory trunk, not the general Galois fixed-class API for the
ambiguous class number formula. -/
def InversionFixedClass (R : Type*) [CommRing R] [IsDomain R] :=
  {C : _root_.ClassGroup R // C = C⁻¹}

/-- The two-torsion subgroup is equivalent to the inversion-fixed classes. -/
def twoTorsionEquivInversionFixedClass (R : Type*) [CommRing R] [IsDomain R] :
    _root_.ClassGroup.twoTorsion R ≃ InversionFixedClass R where
  toFun C := by
    refine ⟨(C : _root_.ClassGroup R), ?_⟩
    have hpow : (C : _root_.ClassGroup R) ^ 2 = 1 := by
      simpa using (_root_.ClassGroup.mem_twoTorsion_iff R C).mp C.2
    have hmul : (C : _root_.ClassGroup R) * C = 1 := by
      simpa [pow_two] using hpow
    exact (eq_inv_iff_mul_eq_one).2 hmul
  invFun C := by
    refine ⟨C.1, ?_⟩
    rw [_root_.ClassGroup.mem_twoTorsion_iff]
    have hmul : (C.1 : _root_.ClassGroup R) * C.1 = 1 := by
      nth_rewrite 1 [C.2]
      rw [inv_mul_cancel]
    simpa [pow_two] using hmul
  left_inv C := by
    ext
    rfl
  right_inv C := by
    apply Subtype.ext
    rfl

/-- The two-torsion subgroup has the same cardinality as the inversion-fixed
classes. This is the formal version of "`σ`-fixed = `Cl[2]`" after
`mk0_map_conjAut_eq_inv`. -/
theorem card_twoTorsion_eq_card_inversionFixedClass
    (R : Type*) [CommRing R] [IsDomain R] :
    Nat.card (_root_.ClassGroup.twoTorsion R) = Nat.card (InversionFixedClass R) :=
  Nat.card_congr (twoTorsionEquivInversionFixedClass R)

/-- **Inversion-fixed class count, indexed by odd ramified primes.** In the
odd fundamental-discriminant branch, all ramified rational primes are odd and
are represented by `oddPrimeDiscriminantDivisors d`. This is the `Cl[2]`
cardinality form supplied mathematically by the ambiguous class number formula:
after `mk0_map_conjAut_eq_inv`, conjugation-fixed ideal classes are identified
with these inversion-fixed classes. -/
theorem card_inversionFixedClass_eq_of_oddPrimeDiscriminantDivisors
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)] (hd_neg : d < 0) (hd4 : d % 4 = 1) :
    Nat.card (InversionFixedClass (𝓞 (Qsqrtd (d : ℚ)))) =
      2 ^ ((oddPrimeDiscriminantDivisors d).card - 1) := by
  sorry

/-- **Inversion-fixed class count, odd-discriminant quadratic case.** This
rewrites the odd-ramified-prime form of the formula using the closed
discriminant prime-factor count `primeDiscriminantFactorCount`. -/
theorem card_inversionFixedClass_eq
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)] (hd_neg : d < 0) (hd4 : d % 4 = 1) :
    Nat.card (InversionFixedClass (𝓞 (Qsqrtd (d : ℚ)))) =
      2 ^ (primeDiscriminantFactorCount d - 1) := by
  have hodd : RingOfIntegers.discrFormula d % 2 ≠ 0 :=
    (RingOfIntegers.discrFormula_odd_iff_mod_four_eq_one d).2 hd4
  rw [← card_oddPrimeDiscriminantDivisors_eq_primeDiscriminantFactorCount_of_discr_odd d hodd]
  exact card_inversionFixedClass_eq_of_oddPrimeDiscriminantDivisors d hd_neg hd4

/-- Genus-theory trunk: the number of genera. For an imaginary quadratic field
`ℚ(√d)` with odd fundamental discriminant (`d % 4 = 1`), the two-torsion subgroup of
the ideal class group has cardinality `2 ^ (t - 1)`, where
`t = primeDiscriminantFactorCount d` is the number of prime-discriminant factors.

This is the standard genus formula in its `Cl[2]` form (`#Cl[2] = #Cl/Cl²`). The
proof boundary is the ambiguous class number formula; see the module docstring. -/
theorem card_classGroup_twoTorsion_eq
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)] (hd_neg : d < 0) (hd4 : d % 4 = 1) :
    Nat.card (_root_.ClassGroup.twoTorsion (𝓞 (Qsqrtd (d : ℚ)))) =
      2 ^ (primeDiscriminantFactorCount d - 1) := by
  rw [card_twoTorsion_eq_card_inversionFixedClass]
  exact card_inversionFixedClass_eq d hd_neg hd4

end ClassGroup
end QuadraticNumberFields
