/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import Mathlib.NumberTheory.NumberField.ClassNumber
import Mathlib.RingTheory.Ideal.Norm.RelNorm
import QuadraticNumberFields.ClassGroup.Torsion
import QuadraticNumberFields.ClassGroup.GenusTheory.Discriminant
import QuadraticNumberFields.QuadraticField.Conj

/-!
# Ambiguous Classes and the Genus-Theory Trunk `#Cl[2] = 2^{t-1}`

This file owns the load-bearing trunk of the genus theory of an imaginary
quadratic field `ℚ(√d)`: the *number of genera*

`#Cl[2] = 2 ^ (t - 1)`,

where `t = primeDiscriminantFactorCount d` is the number of rational primes
dividing the field discriminant. Everything in `GenusTheory/` previously reduced
the genus formula to an unproved surjectivity/bijectivity hypothesis on the odd
genus-character product `Φ`; this file replaces that conditional scaffolding by a
single honest statement and wires `genusFormula_of_mod_four_eq_one` to it.

## Mathematical content and proof boundary

The intended proof is the classical ambiguous class number formula, in its
cohomological form (Hilbert 90 + the periodic cohomology of the cyclic group
`G = Gal(ℚ(√d)/ℚ) = ⟨σ⟩`):

* the conjugation `σ` acts on `Cl` with `σ([I]) = [I]⁻¹` (since `I · σ(I) = (N I)`
  is principal), so the *ambiguous classes* `{C : σ C = C}` are exactly `Cl[2]`;
* `Ĥ⁰(G, I_K) = ⊕_{p ramified} ℤ/2 = (ℤ/2)^t` by cyclic periodicity, and
  `H¹(G, K^×) = 0` by Hilbert 90;
* the two short exact sequences `1 → O_K^× → K^× → P_K → 1` and
  `1 → P_K → I_K → Cl_K → 1` then give `#Cl^G = 2^{t-1}` (the imaginary-quadratic
  unit term is trivial: norms from `ℚ(√d)` are positive, so `-1` is not a norm).

Relative to class field theory this is the *genus fragment*: by reciprocity
`Cl/Cl² ≅ Gal(H_gen/K)` for the genus field `H_gen`, and the genus characters are
the characters of that Galois group. Because mathlib has no reciprocity law, we do
**not** take that shortcut; the ambiguous/cohomological route proves `#Cl[2]`
independently, staying inside Dedekind ring theory plus a thin slice of Galois
cohomology.

## Status

The headline theorem `card_classGroup_twoTorsion_eq` carries the only `sorry`,
pinned exactly on the ambiguous class number formula — the real mathematical
boundary, visible to `sorryAx`/`lean_verify` audits, not hidden behind any
provider or hypothesis.

The ambiguous-class API (`σ`-action on `Cl`, `σ([I]) = [I]⁻¹`,
`ambiguous = Cl[2]`) is the next slice. It requires an induced class-group
automorphism `ClassGroup.map` along a ring automorphism, which mathlib does not
currently provide; it will be built here rather than faked.
-/

open scoped NumberField nonZeroDivisors

namespace QuadraticNumberFields
namespace ClassGroup

attribute [-instance] DivisionRing.toRatAlgebra

/-! ## Ambiguous ideals

An ideal is *ambiguous* when it is fixed by a ring automorphism `σ`. For a
quadratic field `K = ℚ(√d)` the relevant `σ` is the nontrivial Galois
automorphism (conjugation `√d ↦ -√d`); the ambiguous ideals of `𝓞_K` are then the
conjugation-fixed ideals, generated by the rational ideals together with the
ramified primes. The σ-fixed *classes* are exactly `Cl[2]` (because
`σ([I]) = [I]⁻¹`), which is the bridge feeding the genus-theory trunk below.

Here we record the general predicate over an arbitrary ring automorphism;
specializing `σ` to the conjugation of `𝓞(Qsqrtd d)` is the next slice. -/

variable {B : Type*} [CommRing B]

/-- An ideal `I` of `B` is **ambiguous** with respect to a ring automorphism
`σ : B ≃+* B` when it is fixed by `σ`, i.e. `σ(I) = I`. -/
def IsAmbiguousIdeal (σ : B ≃+* B) (I : Ideal B) : Prop :=
  Ideal.map (σ : B →+* B) I = I

/-- Ambiguity of `I` is exactly fixedness of `I` under the pushforward `Ideal.map σ`. -/
theorem isAmbiguousIdeal_iff_isFixedPt (σ : B ≃+* B) (I : Ideal B) :
    IsAmbiguousIdeal σ I ↔ Function.IsFixedPt (Ideal.map (σ : B →+* B)) I :=
  Iff.rfl

/-- The whole ring is ambiguous. -/
theorem isAmbiguousIdeal_top (σ : B ≃+* B) : IsAmbiguousIdeal σ (⊤ : Ideal B) := by
  rw [IsAmbiguousIdeal, Ideal.map_top]

/-- The product of two ambiguous ideals is ambiguous. -/
theorem IsAmbiguousIdeal.mul {σ : B ≃+* B} {I J : Ideal B}
    (hI : IsAmbiguousIdeal σ I) (hJ : IsAmbiguousIdeal σ J) :
    IsAmbiguousIdeal σ (I * J) := by
  unfold IsAmbiguousIdeal at hI hJ ⊢
  rw [Ideal.map_mul, hI, hJ]

/-! ## Conjugation on the ring of integers

The relevant `σ` for a quadratic field `K` is its conjugation
`QuadraticField.conjAut K`, restricted to the ring of integers `𝓞 K`. We obtain
it from mathlib's `RingOfIntegers.mapRingEquiv`. The ambiguous ideals of `𝓞 K`
are then `IsAmbiguousIdeal (conjAutRingOfIntegers K)`. -/

/-- The conjugation of a quadratic field `K`, restricted to its ring of integers
`𝓞 K` as a ring automorphism. This is the `σ` whose fixed ideals are the
ambiguous ideals. -/
noncomputable def conjAutRingOfIntegers (K : Type*) [Field K] [Algebra ℚ K]
    [QuadraticField K] [QuadraticField.Conj K] : 𝓞 K ≃+* 𝓞 K :=
  NumberField.RingOfIntegers.mapRingEquiv (QuadraticField.conjAut K).toRingEquiv

@[simp]
theorem coe_conjAutRingOfIntegers_apply (K : Type*) [Field K] [Algebra ℚ K]
    [QuadraticField K] [QuadraticField.Conj K] (x : 𝓞 K) :
    (conjAutRingOfIntegers K x : K) = QuadraticField.conjAut K x := by
  rw [conjAutRingOfIntegers, NumberField.RingOfIntegers.mapRingEquiv_apply]
  rfl

/-! ## Conjugation acts as inversion on the class group

The bridge `σ([I]) = [I]⁻¹` follows from the principality of `I · σ(I)`: that
product is the extension to `𝓞 K` of the relative norm `relNorm ℤ (𝓞 K) I`, which
is principal because `ℤ` is a PID. Feeding this into `mk0_eq_mk0_inv_iff` shows
conjugation acts on `Cl` by inversion, so the σ-fixed (ambiguous) classes are
exactly `Cl[2]`. -/

section Bridge

variable {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
  [QuadraticField K] [QuadraticField.Conj K]

omit [NumberField K] in
/-- The conjugate of a nonzero ideal is nonzero, since conjugation is bijective. -/
theorem map_conjAut_mem_nonZeroDivisors {I : Ideal (𝓞 K)}
    (hI : I ∈ nonZeroDivisors (Ideal (𝓞 K))) :
    Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) I ∈ nonZeroDivisors (Ideal (𝓞 K)) := by
  simp only [mem_nonZeroDivisors_iff_ne_zero, ne_eq, Ideal.zero_eq_bot,
    Ideal.map_eq_bot_iff_le_ker, RingHom.ker_coe_equiv, le_bot_iff] at hI ⊢
  exact hI

/-- **Crux identity (boundary).** The product `I · σ(I)` of an ideal with its
conjugate equals the extension to `𝓞 K` of the relative norm `relNorm ℤ I`. This
is the ideal-level "product of Galois conjugates equals the relative norm". Mathlib
provides only the prime-case pieces (`relNorm_eq_pow_of_isPrime_isGalois`,
`relNorm_smul`, ...), so the multiplicative-on-primes assembly is left here. -/
theorem mul_map_conjAut_eq_map_relNorm (I : Ideal (𝓞 K)) :
    I * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) I =
      Ideal.map (algebraMap ℤ (𝓞 K)) (Ideal.relNorm ℤ I) := by
  sorry

/-- **Product of an ideal with its conjugate is principal.** For a nonzero ideal
`I` of `𝓞 K`, the product `I · σ(I)` is a nonzero principal ideal: it is the
extension of `relNorm ℤ I`, which is principal because `ℤ` is a PID. -/
theorem exists_span_mul_map_conjAut {I : Ideal (𝓞 K)} (hI : I ≠ ⊥) :
    ∃ x : 𝓞 K, x ≠ 0 ∧
      I * Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) I = Ideal.span {x} := by
  have hrel : Ideal.relNorm ℤ I ≠ ⊥ := by
    rw [ne_eq, ← Ideal.spanNorm_eq, Ideal.spanNorm_eq_bot_iff]; exact hI
  obtain ⟨n, hn⟩ := IsPrincipalIdealRing.principal (Ideal.relNorm ℤ I)
  rw [Ideal.submodule_span_eq] at hn
  have hn0 : n ≠ 0 := by
    rintro rfl
    exact hrel (by rw [hn, Ideal.span_singleton_eq_bot.mpr rfl])
  refine ⟨algebraMap ℤ (𝓞 K) n, ?_, ?_⟩
  · simpa only [map_zero] using (FaithfulSMul.algebraMap_injective ℤ (𝓞 K)).ne hn0
  · rw [mul_map_conjAut_eq_map_relNorm, hn, Ideal.map_span, Set.image_singleton]

/-- **σ([I]) = [I]⁻¹.** Conjugation acts on the ideal class group as inversion: the
class of the conjugate ideal is the inverse class. This is the bridge that turns
the ambiguous (σ-fixed) classes into the two-torsion subgroup `Cl[2]`. -/
theorem mk0_map_conjAut_eq_inv (I : (Ideal (𝓞 K))⁰) :
    ClassGroup.mk0 ⟨Ideal.map (conjAutRingOfIntegers K : 𝓞 K →+* 𝓞 K) (I : Ideal (𝓞 K)),
        map_conjAut_mem_nonZeroDivisors I.2⟩ = (ClassGroup.mk0 I)⁻¹ := by
  have hI : (I : Ideal (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.zero_eq_bot] using mem_nonZeroDivisors_iff_ne_zero.mp I.2
  rw [ClassGroup.mk0_eq_mk0_inv_iff]
  obtain ⟨x, hx0, hx⟩ := exists_span_mul_map_conjAut hI
  exact ⟨x, hx0, by rw [mul_comm]; exact hx⟩

end Bridge

/-! ## Genus-theory trunk -/

/-- Genus-theory trunk: the number of genera. For an imaginary quadratic field
`ℚ(√d)` with odd fundamental discriminant (`d % 4 = 1`), the two-torsion subgroup of
the ideal class group has cardinality `2 ^ (t - 1)`, where
`t = primeDiscriminantFactorCount d` is the number of prime-discriminant factors.

This is the standard genus formula in its `Cl[2]` form (`#Cl[2] = #Cl/Cl²`). The
proof boundary is the ambiguous class number formula; see the module docstring. -/
theorem card_classGroup_twoTorsion_eq
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)] (hd_neg : d < 0) (hd4 : d % 4 = 1) :
    Nat.card (_root_.ClassGroup.twoTorsion (𝓞 (Qsqrtd (d : ℚ)))) =
      2 ^ (primeDiscriminantFactorCount d - 1) := by
  sorry

end ClassGroup
end QuadraticNumberFields
