/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QuadraticNumberFields.RingOfIntegers.CommonInstances
import Examples.SqrtNeg5.ClassNumber
import FormClassGroup.ClassGroup.ClassNumber
import FormClassGroup.ClassGroup.Structure
import BinaryQuadraticForms.Core.Enumeration

/-!
# √-5: Form class group — full theory tour

This file walks through the complete theory chain for `ℚ(√-5)` (the classic
non-UFD quadratic field with class number two).  Each section exercises a
different layer of the project.

## Sections

1. **Invariants** — field discriminant, Minkowski bound
2. **Reduced forms** — enumerate the two reduced BQFs of discriminant -20
3. **Class number** — `NumberField.classNumber (Qsqrtd (-5)) = 2` via both ideal
   and form methods.
4. **Form class group structure** — transported `CommGroup` + Cox multiplicative property
5. **Cox equivalence** — bijection cardinality, non-identity classP

All lemmas are sorry-free.
-/

open scoped NumberField

set_option linter.hashCommand false

attribute [-instance] DivisionRing.toRatAlgebra

noncomputable section

namespace QuadraticNumberFields
namespace Examples
namespace SqrtNeg5

open QuadraticNumberFields.BinaryQuadraticForm

/-! ## 1. Invariants -/

section Invariants

/-- `ℚ(√-5)` has ring of integers `ℤ[√-5]` (`-5 ≡ 3 mod 4` branch). -/
example : (-5 : ℤ) % 4 ≠ 1 := by decide

/-- The field discriminant of `ℚ(√-5)` is `-20`. -/
example : fieldDiscriminant (-5 : ℤ) = -20 := by
  have hd4 : (-5 : ℤ) % 4 ≠ 1 := by decide
  rw [fieldDiscriminant_of_mod_four_ne_one hd4]
  ring

/-- The Minkowski bound for `ℚ(√-5)` is less than 3, so the class group is
generated by ideals of norm ≤ 2. -/
example : Qsqrtd.minkowskiBound (-5 : ℤ) < 3 :=
  minkowskiBound_lt_three

end Invariants

/-! ## 2. Reduced forms of discriminant -20 -/

section ReducedForms

-- There are exactly two primitive reduced positive definite forms of the field
-- discriminant `-20`.
#guard (enumPrimitiveReducedForms (fieldDiscriminant (-5 : ℤ))).card == 2

/-- The principal form `x² + 5y²` is primitive, positive definite, reduced,
and has discriminant -20. -/
example : (BinaryQuadraticForm.mk 1 0 5).disc = -20 := by
  norm_num [disc]

example : (BinaryQuadraticForm.mk 1 0 5).IsPrimitive := by
  norm_num [IsPrimitive]

example : (BinaryQuadraticForm.mk 1 0 5).IsPositiveDefinite := by
  norm_num [IsPositiveDefinite, disc]

example : (BinaryQuadraticForm.mk 1 0 5).IsReduced := by
  norm_num [BinaryQuadraticForm.IsReduced]

/-- The non-principal reduced form is `2x² + 2xy + 3y²`. -/
example : (BinaryQuadraticForm.mk 2 2 3).disc = -20 := by
  norm_num [disc]

example : (BinaryQuadraticForm.mk 2 2 3).IsPrimitive := by
  norm_num [IsPrimitive]

example : (BinaryQuadraticForm.mk 2 2 3).IsPositiveDefinite := by
  norm_num [IsPositiveDefinite, disc]

example : (BinaryQuadraticForm.mk 2 2 3).IsReduced := by
  norm_num [BinaryQuadraticForm.IsReduced]

/-- The two reduced forms are distinct. -/
example : (BinaryQuadraticForm.mk 1 0 5) ≠ (BinaryQuadraticForm.mk 2 2 3) := by
  decide

end ReducedForms

/-! ## 3. Class number via reduced forms -/

section ClassNumber

/-- `ℚ(√-5)` has class number two — the classic non-UFD example. -/
example : NumberField.classNumber (Qsqrtd ((-5 : ℤ) : ℚ)) = 2 :=
  classNumber_eq_two

/-- Computation-path regression for `ℚ(√-5)`: the class number is obtained from
the reduced-form enumeration. -/
theorem classNumber_qsqrtd_neg5_by_reducedForms :
    NumberField.classNumber (Qsqrtd ((-5 : ℤ) : ℚ)) = 2 := by
  compute_class_number_qsqrtd

/-- The class number equals the count of primitive reduced positive definite
forms of the field discriminant.  This is the bridge between ideal-class and
form-class viewpoints. -/
example : NumberField.classNumber (Qsqrtd ((-5 : ℤ) : ℚ)) =
    (enumPrimitiveReducedForms (fieldDiscriminant (-5 : ℤ))).card :=
  classNumber_qsqrtd_eq_reducedForms_card (-5 : ℤ) (by decide : (-5 : ℤ) < 0)

end ClassNumber

/-! ## 4. Form class group structure — transported `CommGroup` -/

section FormClassGroup

/-- The transported `CommGroup` on form classes of discriminant -20.
`formClassCommGroup` is a `def` (not an `instance`), so we make it a local
instance via `letI`. -/
example : CommGroup (FormClass (fieldDiscriminant (-5 : ℤ))) :=
  formClassCommGroup (by decide : (-5 : ℤ) < 0)

/-- Identity in the transported form class group maps to identity in the ideal
class group via the Cox equivalence. -/
example :
    letI := formClassCommGroup (by decide : (-5 : ℤ) < 0)
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0)
      (1 : FormClass (fieldDiscriminant (-5 : ℤ))) =
      (1 : ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) := by
  simpa [formClassCommGroup, Equiv.one_def] using
    Equiv.apply_symm_apply
      (formClassEquivClassGroup (by decide : (-5 : ℤ) < 0)) (1 : ClassGroup _)

/-- Multiplication commutes with the Cox equivalence.  The transported group
law makes the Cox map a homomorphism by construction. -/
example (x y : FormClass (fieldDiscriminant (-5 : ℤ))) :
    letI := formClassCommGroup (by decide : (-5 : ℤ) < 0)
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0) (x * y) =
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0) x *
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0) y :=
  formClassEquivClassGroup_mul (by decide : (-5 : ℤ) < 0) x y

end FormClassGroup

/-! ## 5. Cox equivalence: cardinality -/

section CoxEquivalence

/-- The Cox equivalence is a bijection, so the form class set and the ideal
class group have the same cardinality. -/
example : Fintype.card (FormClass (fieldDiscriminant (-5 : ℤ))) =
    Fintype.card (ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) := by
  classical
  exact Fintype.card_congr (formClassEquivClassGroup (by decide : (-5 : ℤ) < 0))

/-- `classP` is the non-identity element of the ideal class group.
The Cox equivalence guarantees a corresponding non-identity form class. -/
example : classP ≠ (1 : ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) :=
  classP_ne_one

end CoxEquivalence

end SqrtNeg5
end Examples
end QuadraticNumberFields
