/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QNFMathlib.RingTheory.Ideal.Norm.AbsNorm
import QuadraticNumberFields.ClassGroup.Ambiguous.RamifiedParity
import QuadraticNumberFields.ClassGroup.Ambiguous.Relation.SquareNorm
import QuadraticNumberFields.ClassGroup.Narrow.Principal
import QuadraticNumberFields.Splitting.Qsqrtd.SqrtD

/-!
# Imaginary-Quadratic Layer for the Ramified-Parity Relation

The `d = -1` Gaussian-integer special case, the `d ≠ -1` sqrtdSpan nonzero-parity
lemma, principal ambiguous-ideal existence, and ordinary/positive ramified-parity
generators for imaginary fields.
-/

namespace QuadraticNumberFields
namespace ClassGroup
namespace Ambiguous

open scoped NumberField nonZeroDivisors
open scoped QuadraticNumberFields.Splitting

attribute [-instance] DivisionRing.toRatAlgebra

section Qsqrtd

variable (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]

local notation "OK" => NumberField.RingOfIntegers (Qsqrtd (d : ℚ))
local notation "conjOK" => conjAutRingOfIntegers (Qsqrtd (d : ℚ))

/-- For `d ≠ -1`, the principal ideal generated by `√d` has nonzero full
ramified parity. -/
private theorem exists_nonzero_fullRamifiedParityVector_span_sqrtdInt_of_ne_neg_one
    (hdm1 : d ≠ -1) :
    ∃ p, fullRamifiedParityVector d (Splitting.sqrtdSpanNonzeroIdeal d) p ≠ 0 := by
  classical
  let J : (Ideal OK)⁰ := Splitting.sqrtdSpanNonzeroIdeal d
  have hdabs_ne_one : d.natAbs ≠ 1 := by
    intro h
    rcases Int.isUnit_iff.mp (Int.isUnit_iff_natAbs_eq.mpr h) with hd | hd
    · exact (Fact.out : d ≠ 1) hd
    · exact hdm1 hd
  obtain ⟨p, hp, hpdvd⟩ := Nat.exists_prime_and_dvd hdabs_ne_one
  let pr : RamifiedPrimeIndex d :=
    ramifiedPrimeIndexOfNatAbsDvd d hp hpdvd
  have hpr : (pr : ℕ) = p := by
    simp [pr, ramifiedPrimeIndexOfNatAbsDvd]
  by_contra hnone
  have hzero : fullRamifiedParityVector d J pr = 0 := by
    by_contra hne
    exact hnone ⟨pr, hne⟩
  have hJ0 : (J : Ideal OK) ≠ ⊥ :=
    mem_nonZeroDivisors_iff_ne_zero.mp J.2
  have hnormJ : Ideal.absNorm (J : Ideal OK) = d.natAbs := by
    simpa [J] using absNorm_span_sqrtdInt d
  have hpdivJ : p ∣ Ideal.absNorm (J : Ideal OK) := by
    simpa [hnormJ] using hpdvd
  obtain ⟨P, hPmem, hPover⟩ :=
    Ideal.exists_normalizedFactor_mem_primesOver_of_nat_prime_dvd_absNorm
      hJ0 hp hpdivJ
  have hP_eq : P = ramifiedPrimeIdeal d pr := by
    have hPover' : P ∈ Ideal.primesOver (𝔭(pr.1)) OK := by
      simpa [hpr] using hPover
    rw [primesOver_eq_singleton_ramifiedPrimeIdeal d pr] at hPover'
    simpa using hPover'
  have hramMem : ramifiedPrimeIdeal d pr ∈
      UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK) := by
    simpa [hP_eq] using hPmem
  have hcount2 :=
    two_le_count_of_fullRamifiedParityVector_eq_zero_of_mem d hzero hramMem
  have hnorm_sq_dvd :
      Ideal.absNorm (ramifiedPrimeIdeal d pr) ^ 2 ∣ Ideal.absNorm (J : Ideal OK) :=
    Ideal.absNorm_sq_dvd_of_two_le_normalizedFactors_count hJ0 hcount2
  have hp_dvd_normP : p ∣ Ideal.absNorm (ramifiedPrimeIdeal d pr) := by
    have hdiv :
        Ideal.absNorm ((ramifiedPrimeIdeal d pr).under ℤ) ∣
          Ideal.absNorm (ramifiedPrimeIdeal d pr) :=
      Int.absNorm_under_dvd_absNorm (ramifiedPrimeIdeal d pr)
    have hunder : (ramifiedPrimeIdeal d pr).under ℤ = 𝔭(p) := by
      simpa [hpr] using (ramifiedPrimeIdeal_mem_primesOver d pr).2.1.symm
    have habs : Ideal.absNorm (𝔭(p) : Ideal ℤ) = p := by
      rw [Ideal.absNorm_span_singleton]
      change (Algebra.norm ℤ (p : ℤ)).natAbs = p
      simp
    rw [hunder, habs] at hdiv
    exact hdiv
  have hnot := not_absNorm_sq_dvd_squarefree_natAbs d hp hp_dvd_normP
  rw [hnormJ] at hnorm_sq_dvd
  exact hnot hnorm_sq_dvd


private theorem algebraNorm_one_add_sqrtdInt_neg_one :
    Algebra.norm ℤ
        ((1 + Splitting.sqrtdInt (-1)) :
          NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ))) =
      2 := by
  apply Int.cast_injective (α := ℚ)
  rw [Algebra.coe_norm_int (K := Qsqrtd ((-1 : ℤ) : ℚ)),
    Qsqrtd.algebraNorm_ratAlgebra_eq_qsqrtdNorm]
  have hcoord :
      (((1 + Splitting.sqrtdInt (-1)) :
          NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ))) :
        Qsqrtd ((-1 : ℤ) : ℚ)) =
        (⟨1, 1⟩ : Qsqrtd ((-1 : ℤ) : ℚ)) := by
    haveI : Fact (Squarefree (-1 : ℤ)) := ⟨by norm_num⟩
    haveI : Fact ((-1 : ℤ) ≠ 1) := ⟨by norm_num⟩
    let K := Qsqrtd ((-1 : ℤ) : ℚ)
    let R := NumberField.RingOfIntegers K
    have hsrc :
        (1 + Splitting.sqrtdInt (-1) : R) =
          algebraMap ℤ R 1 + algebraMap ℤ R 1 * Splitting.sqrtdInt (-1) := by
      norm_num
    rw [hsrc]
    exact Splitting.coe_intCast_add_intCast_mul_sqrtdInt (-1) 1 1
  rw [hcoord]
  norm_num [Qsqrtd.norm, QuadraticAlgebra.norm]

private theorem absNorm_span_one_add_sqrtdInt_neg_one :
    Ideal.absNorm
        (Ideal.span
          ({(1 + Splitting.sqrtdInt (-1))} :
            Set (NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ))))) =
      2 := by
  rw [Ideal.absNorm_span_singleton, algebraNorm_one_add_sqrtdInt_neg_one]
  norm_num

private theorem one_add_sqrtdInt_mul_one_sub_sqrtdInt_neg_one :
    ((1 + Splitting.sqrtdInt (-1)) * (1 - Splitting.sqrtdInt (-1)) :
      NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ))) = 2 := by
  let K := Qsqrtd ((-1 : ℤ) : ℚ)
  let R := NumberField.RingOfIntegers K
  apply NumberField.RingOfIntegers.ext
  change (((1 + Splitting.sqrtdInt (-1) : R) : K) *
      ((1 - Splitting.sqrtdInt (-1) : R) : K)) = (2 : K)
  have hleft : ((1 + Splitting.sqrtdInt (-1) : R) : K) = (⟨1, 1⟩ : K) := by
    haveI : Fact (Squarefree (-1 : ℤ)) := ⟨by norm_num⟩
    haveI : Fact ((-1 : ℤ) ≠ 1) := ⟨by norm_num⟩
    have hsrc :
        (1 + Splitting.sqrtdInt (-1) : R) =
          algebraMap ℤ R 1 + algebraMap ℤ R 1 * Splitting.sqrtdInt (-1) := by
      norm_num
    rw [hsrc]
    exact Splitting.coe_intCast_add_intCast_mul_sqrtdInt (-1) 1 1
  have hright : ((1 - Splitting.sqrtdInt (-1) : R) : K) = (⟨1, -1⟩ : K) := by
    haveI : Fact (Squarefree (-1 : ℤ)) := ⟨by norm_num⟩
    haveI : Fact ((-1 : ℤ) ≠ 1) := ⟨by norm_num⟩
    have hsrc :
        (1 - Splitting.sqrtdInt (-1) : R) =
          algebraMap ℤ R 1 - algebraMap ℤ R 1 * Splitting.sqrtdInt (-1) := by
      norm_num
    rw [hsrc]
    exact Splitting.coe_intCast_sub_intCast_mul_sqrtdInt (-1) 1 1
  rw [hleft, hright]
  apply QuadraticAlgebra.ext
  · change (1 : ℚ) * 1 + ((-1 : ℤ) : ℚ) * 1 * (-1) = (2 : K).re
    simp [QuadraticAlgebra.re_ofNat]
    norm_num
  · change (1 : ℚ) * (-1) + 1 * 1 + (0 : ℚ) * 1 * (-1) = (2 : K).im
    simp [QuadraticAlgebra.im_ofNat]

private theorem span_one_add_sqrtdInt_neg_one_mem_primesOver_two :
    Ideal.span
        ({(1 + Splitting.sqrtdInt (-1))} :
          Set (NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ)))) ∈
      Ideal.primesOver (𝔭(2))
        (NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ))) := by
  let R := NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ))
  let I : Ideal R := Ideal.span ({(1 + Splitting.sqrtdInt (-1))} : Set R)
  have hIprime : I.IsPrime := by
    have hnorm : Ideal.absNorm I = 2 := by
      unfold I
      exact absNorm_span_one_add_sqrtdInt_neg_one
    exact Ideal.isPrime_of_irreducible_absNorm
      (hnorm ▸ (Nat.irreducible_iff_prime.mp Nat.prime_two).irreducible)
  refine ⟨hIprime, ?_⟩
  have h2mem : (2 : R) ∈ I := by
    change (2 : R) ∈ Ideal.span ({(1 + Splitting.sqrtdInt (-1))} : Set R)
    rw [Ideal.mem_span_singleton]
    refine ⟨(1 - Splitting.sqrtdInt (-1) : R), ?_⟩
    exact one_add_sqrtdInt_mul_one_sub_sqrtdInt_neg_one.symm
  have hle : (𝔭(2) : Ideal ℤ) ≤ I.comap (algebraMap ℤ R) := by
    simpa [Ideal.span_singleton_le_iff_mem] using h2mem
  have hmax : (𝔭(2) : Ideal ℤ).IsMaximal := Splitting.pIdeal_isMaximal Nat.prime_two
  have hne : I.comap (algebraMap ℤ R) ≠ ⊤ :=
    Ideal.comap_ne_top (algebraMap ℤ R) hIprime.ne_top
  exact ⟨hmax.eq_of_le hne hle⟩

/-- The rational prime `2` as a ramified-prime index for `ℚ(√-1)`. -/
private noncomputable def ramifiedPrimeIndexTwoNegOne : RamifiedPrimeIndex (-1) :=
  ⟨2, by
    rw [mem_ramifiedPrimes_iff, RingOfIntegers.discr_gaussian]
    norm_num⟩

/-- The indexed ramified prime ideal above `2` in `ℚ(√-1)` is principal. -/
private theorem ramifiedPrimeIdeal_two_neg_one_isPrincipal :
    (ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne :
      Ideal (NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ)))).IsPrincipal := by
  let R := NumberField.RingOfIntegers (Qsqrtd ((-1 : ℤ) : ℚ))
  let I : Ideal R := Ideal.span ({(1 + Splitting.sqrtdInt (-1))} : Set R)
  have hI_mem : I ∈ Ideal.primesOver (𝔭(2)) R := by
    simpa [I, R] using span_one_add_sqrtdInt_neg_one_mem_primesOver_two
  have hIeq : I = ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne := by
    have hsingleton :=
      primesOver_eq_singleton_ramifiedPrimeIdeal
        (-1) ramifiedPrimeIndexTwoNegOne
    have hmem_single :
        I ∈ ({ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne} :
            Set (Ideal R)) := by
      have hsingletonR :
          Ideal.primesOver (𝔭(2)) R =
            {ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne} := by
        simpa [R, ramifiedPrimeIndexTwoNegOne] using hsingleton
      simpa [hsingletonR] using hI_mem
    exact Set.mem_singleton_iff.mp hmem_single
  rw [← hIeq]
  change (Ideal.span ({(1 + Splitting.sqrtdInt (-1))} : Set R)).IsPrincipal
  exact ⟨1 + Splitting.sqrtdInt (-1), rfl⟩

/-- There is a principal ambiguous integral ideal with nonzero ramified parity. -/
private theorem exists_principal_ambiguousIdeal_with_nonzero_fullRamifiedParityVector :
    ∃ J : (Ideal OK)⁰,
      IsAmbiguousIdeal conjOK (J : Ideal OK) ∧
        (J : Ideal OK).IsPrincipal ∧ ∃ p, fullRamifiedParityVector d J p ≠ 0 := by
  classical
  let J : (Ideal OK)⁰ := Splitting.sqrtdSpanNonzeroIdeal d
  by_cases hJparity : ∃ p, fullRamifiedParityVector d J p ≠ 0
  · refine ⟨J, ?_, ?_, hJparity⟩
    · change
        Ideal.map (conjOK : OK →+* OK)
            (Ideal.span ({Splitting.sqrtdInt d} : Set OK)) =
          Ideal.span ({Splitting.sqrtdInt d} : Set OK)
      rw [Ideal.map_span, Set.image_singleton]
      have hmap :
          conjOK (Splitting.sqrtdInt d) =
            -Splitting.sqrtdInt d := by
        simpa using Splitting.conjAutRingOfIntegers_intCast_add_intCast_mul_sqrtdInt d 0 1
      simp [hmap, Ideal.span_singleton_neg]
    · change (Ideal.span ({Splitting.sqrtdInt d} : Set OK)).IsPrincipal
      infer_instance
  · by_cases hdm1 : d = -1
    · subst d
      let R := NumberField.RingOfIntegers (Qsqrtd (((-1 : ℤ)) : ℚ))
      let J : (Ideal R)⁰ :=
        ⟨ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            (ramifiedPrimeIdeal_ne_bot (-1) ramifiedPrimeIndexTwoNegOne)⟩
      refine ⟨J, ?_, ?_, ?_⟩
      · change Ideal.map
            (conjAutRingOfIntegers (Qsqrtd (((-1 : ℤ)) : ℚ)) : R →+* R)
            (ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne) =
          ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne
        exact isAmbiguousIdeal_ramifiedPrimeIdeal
          (-1) ramifiedPrimeIndexTwoNegOne
      · change (ramifiedPrimeIdeal (-1) ramifiedPrimeIndexTwoNegOne :
            Ideal R).IsPrincipal
        exact ramifiedPrimeIdeal_two_neg_one_isPrincipal
      · exact ⟨ramifiedPrimeIndexTwoNegOne,
          fullRamifiedParityVector_ramifiedPrimeNonzeroIdeal_self_ne_zero
            (-1) ramifiedPrimeIndexTwoNegOne⟩
    · exact False.elim <| hJparity <| by
        simpa [J] using
          exists_nonzero_fullRamifiedParityVector_span_sqrtdInt_of_ne_neg_one d hdm1

/-- Ordinary-principal ramified parity relation as an integral ideal statement. -/
private theorem exists_nonzero_ramifiedParity_isPrincipal :
    ∃ r : RamifiedParityVector d,
      (∃ p, r p ≠ 0) ∧ (fullRamifiedParityIdealProduct d r : Ideal OK).IsPrincipal := by
  classical
  obtain ⟨J, hJamb, hJprincipal, hJparity⟩ :=
    exists_principal_ambiguousIdeal_with_nonzero_fullRamifiedParityVector d
  let r := fullRamifiedParityVector d J
  refine ⟨r, hJparity, ?_⟩
  have hnarrow :
      NarrowClassGroup.mk0 J =
        NarrowClassGroup.mk0 (fullRamifiedParityIdealProduct d r) := by
    rw [mk0_fullRamifiedParityIdealProduct]
    simpa [r] using ambiguousIdeal_mk0_eq_fullRamifiedParityNarrowClassHom d J hJamb
  have hwide := congrArg (NarrowClassGroup.toClassGroup OK) hnarrow
  have hJwide : ClassGroup.mk0 J = (1 : ClassGroup OK) :=
    (ClassGroup.mk0_eq_one_iff J.2).mpr hJprincipal
  have hfullwide :
      ClassGroup.mk0 (fullRamifiedParityIdealProduct d r) = (1 : ClassGroup OK) := by
    simpa [NarrowClassGroup.toClassGroup_mk0] using hwide.symm.trans hJwide
  exact (ClassGroup.mk0_eq_one_iff (fullRamifiedParityIdealProduct d r).2).mp hfullwide

/-- Ordinary-principal ramified parity relation with a fraction-field generator. -/
private theorem exists_nonzero_ramifiedParity_principal_generator :
    ∃ r : RamifiedParityVector d,
      (∃ p, r p ≠ 0) ∧
        ∃ γ : (FractionRing OK)ˣ,
          toPrincipalIdeal OK (FractionRing OK) γ =
            FractionalIdeal.mk0 (FractionRing OK) (fullRamifiedParityIdealProduct d r) := by
  classical
  obtain ⟨r, hrnonzero, hprincipal⟩ :=
    exists_nonzero_ramifiedParity_isPrincipal d
  obtain ⟨γ, hγ⟩ :=
    NarrowClassGroup.exists_toPrincipalIdeal_eq_mk0_of_isPrincipal
      (I := fullRamifiedParityIdealProduct d r) hprincipal
  exact ⟨r, hrnonzero, γ, hγ⟩


/-- In the imaginary quadratic case, ordinary-principal ramified parity
relations are automatically positive-principal: total positivity is vacuous. -/
private theorem exists_nonzero_ramifiedParity_tp_generator_of_imaginary_of_principal_generator
    (hd : d < 0)
    (hprincipal :
      ∃ r : RamifiedParityVector d,
        (∃ p, r p ≠ 0) ∧
          ∃ γ : (FractionRing OK)ˣ,
            toPrincipalIdeal OK (FractionRing OK) γ =
              FractionalIdeal.mk0 (FractionRing OK) (fullRamifiedParityIdealProduct d r)) :
    ∃ r : RamifiedParityVector d,
      (∃ p, r p ≠ 0) ∧
        ∃ γ : (FractionRing OK)ˣ,
          NarrowClassGroup.IsTotallyPositive (γ : FractionRing OK) ∧
            toPrincipalIdeal OK (FractionRing OK) γ =
              FractionalIdeal.mk0 (FractionRing OK) (fullRamifiedParityIdealProduct d r) := by
  classical
  letI : IsEmpty (FractionRing OK →+* ℝ) := by
    simpa using
      QuadraticNumberFields.Qsqrtd.Imaginary.isEmpty_fractionRing_realEmbeddings d hd
  obtain ⟨r, hrnonzero, γ, hγ⟩ := hprincipal
  exact ⟨r, hrnonzero, γ,
    NarrowClassGroup.isTotallyPositive_of_isEmpty (γ : FractionRing OK), hγ⟩

/-- Imaginary-quadratic positive-principal ramified parity relation. -/
theorem exists_nonzero_ramifiedParity_tp_generator_of_imaginary
    (hd : d < 0) :
    ∃ r : RamifiedParityVector d,
      (∃ p, r p ≠ 0) ∧
        ∃ γ : (FractionRing OK)ˣ,
          NarrowClassGroup.IsTotallyPositive (γ : FractionRing OK) ∧
            toPrincipalIdeal OK (FractionRing OK) γ =
              FractionalIdeal.mk0 (FractionRing OK) (fullRamifiedParityIdealProduct d r) :=
  exists_nonzero_ramifiedParity_tp_generator_of_imaginary_of_principal_generator d hd
    (exists_nonzero_ramifiedParity_principal_generator d)


end Qsqrtd

end Ambiguous
end ClassGroup
end QuadraticNumberFields
