/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QNFMathlib.RingTheory.Ideal.Norm.AbsNorm
import QuadraticNumberFields.ClassGroup.Ambiguous.RamifiedParity
import QuadraticNumberFields.ClassGroup.Narrow.Principal
import QuadraticNumberFields.Splitting.Qsqrtd.SqrtD

/-!
# Square-Norm Layer for the Ramified-Parity Relation

This file develops the absolute-norm factorization and `IsSquare`
involution-product combinatorics needed for the capstone theorem
`isSquare_absNorm_of_isAmbiguousIdeal_of_forall_fullRamifiedParityVector_eq_zero`.
-/

namespace QuadraticNumberFields
namespace ClassGroup
namespace Ambiguous

open scoped NumberField nonZeroDivisors
open scoped QuadraticNumberFields.Splitting

attribute [-instance] DivisionRing.toRatAlgebra

section Qsqrtd

variable (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]

local notation "OK" => NumberField.RingOfIntegers (Qsqrtd (d : ℚ))
local notation "conjOK" => conjAutRingOfIntegers (Qsqrtd (d : ℚ))

private theorem algebraNorm_sqrtdInt :
    Algebra.norm ℤ (Splitting.sqrtdInt d) = -d := by
  apply Int.cast_injective (α := ℚ)
  rw [Algebra.coe_norm_int (K := Qsqrtd (d : ℚ))]
  simp [ Qsqrtd.algebraNorm_ratAlgebra_eq_qsqrtdNorm,
  Qsqrtd.norm, QuadraticAlgebra.norm, QuadraticAlgebra.omega]

/-- The principal ideal generated by the integral `√d` has absolute norm `|d|`. -/
theorem absNorm_span_sqrtdInt :
    Ideal.absNorm (Ideal.span ({Splitting.sqrtdInt d} : Set OK)) =
      d.natAbs := by
  simp [Ideal.absNorm_span_singleton, algebraNorm_sqrtdInt d]

omit [Fact (d ≠ 1)] in
/-- For squarefree `d`, no square carrying a prime factor can divide `|d|`. -/
theorem not_absNorm_sq_dvd_squarefree_natAbs
    {p n : ℕ} (hp : p.Prime) (hpn : p ∣ n) :
    ¬ n ^ 2 ∣ d.natAbs := by
  intro hn2
  have hsq_nat : Squarefree d.natAbs := Int.squarefree_natAbs.mpr (Fact.out : Squarefree d)
  have hp2_dvd_n2 : p ^ 2 ∣ n ^ 2 := by
    simpa [pow_two] using mul_dvd_mul hpn hpn
  have hp2_dvd_d : p ^ 2 ∣ d.natAbs := dvd_trans hp2_dvd_n2 hn2
  exact Squarefree.not_mul_self_dvd_of_not_isUnit hsq_nat (p := p)
    hp.not_isUnit (by simpa [pow_two] using hp2_dvd_d)

private theorem two_dvd_count_ramifiedPrimeIdeal_of_fullRamifiedParityVector_eq_zero
    (J : (Ideal OK)⁰)
    (p : RamifiedPrimeIndex d)
    (hparity : fullRamifiedParityVector d J p = 0) :
    2 ∣ (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).count
        (ramifiedPrimeIdeal d p) := by
  let s := UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)
  let n := s.count (ramifiedPrimeIdeal d p)
  have hmod : n % 2 = 0 := by
    have hval := congrArg ZMod.val hparity
    simpa [fullRamifiedParityVector, n, s, ZMod.val_natCast] using hval
  exact Nat.dvd_of_mod_eq_zero hmod

/-- A zero ramified-parity coordinate and actual membership of the ramified
prime ideal force its normalized-factor count to be at least two. -/
theorem two_le_count_of_fullRamifiedParityVector_eq_zero_of_mem
    {J : (Ideal OK)⁰}
    {p : RamifiedPrimeIndex d}
    (hparity : fullRamifiedParityVector d J p = 0)
    (hmem : ramifiedPrimeIdeal d p ∈
      UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)) :
    2 ≤ (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).count
        (ramifiedPrimeIdeal d p) := by
  let s := UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)
  let n := s.count (ramifiedPrimeIdeal d p)
  have hpos : 0 < n := by
    simpa [n, s] using (Multiset.count_pos.mpr hmem)
  have h2dvd : 2 ∣ n := by
    simpa [n, s] using
      two_dvd_count_ramifiedPrimeIdeal_of_fullRamifiedParityVector_eq_zero d J p hparity
  change 2 ≤ n
  exact Nat.one_lt_of_ne_zero_of_even (Nat.ne_of_gt hpos)
    (even_iff_two_dvd.mpr h2dvd)

private theorem isSquare_finset_prod_of_involution
    {α M : Type*} [CommMonoid M]
    (s : Finset α) (f : α → M) (σ : α → α)
    (hσmem : ∀ a ∈ s, σ a ∈ s)
    (hσinv : ∀ a ∈ s, σ (σ a) = a)
    (hfixed : ∀ a ∈ s, σ a = a → IsSquare (f a))
    (hpair : ∀ a ∈ s, σ a ≠ a → f (σ a) = f a) :
    IsSquare (∏ a ∈ s, f a) := by
  classical
  refine Finset.strongInduction
    (p := fun t =>
      (∀ a ∈ t, σ a ∈ t) →
      (∀ a ∈ t, σ (σ a) = a) →
      (∀ a ∈ t, σ a = a → IsSquare (f a)) →
      (∀ a ∈ t, σ a ≠ a → f (σ a) = f a) →
      IsSquare (∏ a ∈ t, f a)) ?_ s hσmem hσinv hfixed hpair
  intro t ih hσmem hσinv hfixed hpair
  obtain rfl | ⟨a, ha⟩ := t.eq_empty_or_nonempty
  · simp
  let p : Finset α := {a, σ a}
  have hp_subset : p ⊆ t := by
    intro x hx
    rw [Finset.mem_insert] at hx
    rcases hx with rfl | hx
    · exact ha
    · rw [Finset.mem_singleton] at hx
      rw [hx]
      exact hσmem a ha
  have hp_sq : IsSquare (∏ b ∈ p, f b) := by
    by_cases hσa : σ a = a
    · simpa [p, hσa] using hfixed a ha hσa
    · have hpair_sq : IsSquare (f a * f (σ a)) := by
        simp [hpair a ha hσa]
      simpa [p, Finset.prod_pair (Ne.symm hσa)] using hpair_sq
  have hrest : IsSquare (∏ b ∈ t \ p, f b) := by
    refine ih (t \ p) (Finset.sdiff_ssubset hp_subset ⟨a, by simp [p]⟩) ?_ ?_ ?_ ?_
    · intro b hb
      rw [Finset.mem_sdiff] at hb ⊢
      refine ⟨hσmem b hb.1, ?_⟩
      intro hσb_mem_p
      have hb_mem_p : b ∈ p := by
        rw [Finset.mem_insert] at hσb_mem_p
        rcases hσb_mem_p with hσb | hσb
        · have hb_eq : b = σ a := by
            calc
              b = σ (σ b) := (hσinv b hb.1).symm
              _ = σ a := by rw [hσb]
          simp [p, hb_eq]
        · rw [Finset.mem_singleton] at hσb
          have hb_eq : b = a := by
            calc
              b = σ (σ b) := (hσinv b hb.1).symm
              _ = σ (σ a) := by rw [hσb]
              _ = a := hσinv a ha
          simp [p, hb_eq]
      exact hb.2 hb_mem_p
    · intro b hb
      exact hσinv b (Finset.mem_sdiff.mp hb).1
    · intro b hb hbfix
      exact hfixed b (Finset.mem_sdiff.mp hb).1 hbfix
    · intro b hb hbne
      exact hpair b (Finset.mem_sdiff.mp hb).1 hbne
  rw [← Finset.prod_sdiff hp_subset]
  exact hrest.mul hp_sq

private theorem absNorm_eq_prime_pow_inertiaDeg_of_comap_eq_p
    {P : Ideal OK}
    [P.IsPrime]
    {p : ℕ}
    (hcomap : P.comap (algebraMap ℤ OK) = 𝔭(p)) :
    Ideal.absNorm P = p ^ P.inertiaDeg ℤ := by
  letI : P.LiesOver (𝔭(p)) := ⟨hcomap.symm⟩
  exact (Ideal.pow_inertiaDeg p P).symm

private theorem absNorm_eq_prime_sq_of_isInertIn_of_comap_eq_p
    {P : Ideal OK}
    (hPprime : P.IsPrime) {p : ℕ} (hp : p.Prime)
    (hcomap : P.comap (algebraMap ℤ OK) = 𝔭(p))
    (hinert : Ideal.IsInertIn (𝔭(p)) OK) :
    Ideal.absNorm P = p ^ 2 := by
  have hpbot : (𝔭(p)) ≠ (⊥ : Ideal ℤ) := Splitting.pIdeal_ne_bot hp
  haveI : (𝔭(p)).IsMaximal := Splitting.pIdeal_isMaximal hp
  letI : P.IsPrime := hPprime
  letI : P.LiesOver (𝔭(p)) := ⟨hcomap.symm⟩
  rw [absNorm_eq_prime_pow_inertiaDeg_of_comap_eq_p d hcomap,
    Ideal.inertiaDeg_eq_two_of_isInertIn (p := 𝔭(p)) (S := OK)
      (by norm_num : ringChar ℤ ≠ 2) hpbot hinert]

private theorem normalizedFactors_ramified_absNorm_count_prod_eq_ramifiedPrime_count_prod
    (J : (Ideal OK)⁰)
    [DecidablePred (fun P :
        {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)} =>
      normalizedFactorIsRamified d P)] :
    (∏ P ∈
        (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).attach.toFinset with
        normalizedFactorIsRamified d P,
      Ideal.absNorm P.1 ^
        (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).count P.1) =
      Finset.univ.prod fun p : RamifiedPrimeIndex d =>
        Ideal.absNorm (ramifiedPrimeIdeal d p) ^
          (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).count
            (ramifiedPrimeIdeal d p) := by
  classical
  let s := UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)
  let S := s.attach.toFinset
  let f : {P // P ∈ s} → ℕ := fun P => Ideal.absNorm P.1 ^ s.count P.1
  let term : RamifiedPrimeIndex d → ℕ := fun p =>
    Ideal.absNorm (ramifiedPrimeIdeal d p) ^
      s.count (ramifiedPrimeIdeal d p)
  let T := Finset.univ.filter fun p : RamifiedPrimeIndex d =>
    ramifiedPrimeIdeal d p ∈ s
  have hleft :
      (∏ P ∈ S with normalizedFactorIsRamified d P, f P) = ∏ p ∈ T, term p := by
    simpa [T] using
      normalizedFactors_ramified_prod_eq_ramifiedPrimeIndex_filter_prod d J f term (by
        intro P hPram
        let p := ramifiedPrimeIndexOfNormalizedFactor d P hPram
        have hP_eq :
            P.1 = ramifiedPrimeIdeal d p :=
          normalizedFactor_eq_ramifiedPrimeIdeal_ramifiedPrimeIndexOfNormalizedFactor
            d P hPram
        dsimp [f, term, p]
        rw [hP_eq])
  have hright :
      (∏ p ∈ T, term p) =
        Finset.univ.prod fun p : RamifiedPrimeIndex d =>
          Ideal.absNorm (ramifiedPrimeIdeal d p) ^
            (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).count
              (ramifiedPrimeIdeal d p) := by
    simpa [T, term, s] using
      ramifiedPrimeIndex_filter_prod_eq_univ_prod_of_not_mem_eq_one d J term (by
        intro p hmem
        have hcount0 : s.count (ramifiedPrimeIdeal d p) = 0 :=
          Multiset.count_eq_zero_of_notMem hmem
        simp [term, hcount0])
  simpa [f, s, S] using hleft.trans hright

private theorem isSquare_ramified_absNorm_count_prod_of_forall_fullRamifiedParityVector_eq_zero
    (J : (Ideal OK)⁰)
    (hparity : ∀ p, fullRamifiedParityVector d J p = 0)
    [DecidablePred (fun P :
        {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)} =>
      normalizedFactorIsRamified d P)] :
    IsSquare
      (∏ P ∈
          (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).attach.toFinset with
          normalizedFactorIsRamified d P,
        Ideal.absNorm P.1 ^
          (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).count P.1) := by
  rw [normalizedFactors_ramified_absNorm_count_prod_eq_ramifiedPrime_count_prod d J]
  refine Finset.isSquare_prod _ ?_
  intro p _hp
  exact Even.isSquare_pow
    (even_iff_two_dvd.mpr
      (two_dvd_count_ramifiedPrimeIdeal_of_fullRamifiedParityVector_eq_zero
        d J p (hparity p)))
    (Ideal.absNorm (ramifiedPrimeIdeal d p))

private theorem isSquare_nonramified_absNorm_count_prod_of_isAmbiguousIdeal
    (J : (Ideal OK)⁰)
    (hJ : IsAmbiguousIdeal conjOK (J : Ideal OK))
    [DecidablePred (fun P :
        {P // P ∈ UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)} =>
      ¬ normalizedFactorIsRamified d P)] :
    IsSquare
      (∏ P ∈
          (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).attach.toFinset with
          ¬ normalizedFactorIsRamified d P,
        Ideal.absNorm P.1 ^
          (UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)).count P.1) := by
  classical
  let s := UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)
  let S := s.attach.toFinset.filter fun P => ¬ normalizedFactorIsRamified d P
  let f : {P // P ∈ s} → ℕ := fun P => Ideal.absNorm P.1 ^ s.count P.1
  let σ : {P // P ∈ s} → {P // P ∈ s} := conjAutNormalizedFactor (Qsqrtd (d : ℚ)) hJ
  change IsSquare (∏ P ∈ S, f P)
  refine isSquare_finset_prod_of_involution S f σ ?_ ?_ ?_ ?_
  · intro P hP
    rw [Finset.mem_filter] at hP ⊢
    refine ⟨by simp [σ], ?_⟩
    intro hσram
    exact hP.2 ((normalizedFactorIsRamified_conjAutNormalizedFactor_iff d hJ P).mp hσram)
  · intro P _hP
    exact conjAutNormalizedFactor_involutive (Qsqrtd (d : ℚ)) hJ P
  · intro P hP hfix
    rw [Finset.mem_filter] at hP
    have hPnonram : ¬ normalizedFactorIsRamified d P := hP.2
    have hJ0 : (J : Ideal OK) ≠ ⊥ := by
      simpa [Ideal.zero_eq_bot] using mem_nonZeroDivisors_iff_ne_zero.mp J.2
    have hPdata := (Ideal.mem_normalizedFactors_iff hJ0).mp P.2
    have hP0 : P.1 ≠ ⊥ :=
      fun hPbot => hJ0 (le_bot_iff.mp (by simpa [hPbot] using hPdata.2))
    obtain ⟨p, hp, hcomap, _hdvd⟩ :=
      Ideal.exists_nat_prime_comap_eq_span_and_dvd_absNorm_of_isPrime hPdata.1 hP0
    rcases factor_contribution_cases_narrowClass d hJ P hp hcomap with
      hsplit | hinert | hram
    · have hne :=
        conjAutNormalizedFactor_ne_of_isSplitIn
          (Qsqrtd (d : ℚ)) hJ P hp hcomap hsplit.1
      exact False.elim (hne hfix)
    · have hnorm : Ideal.absNorm P.1 = p ^ 2 :=
        absNorm_eq_prime_sq_of_isInertIn_of_comap_eq_p d hPdata.1 hp hcomap hinert.1
      dsimp [f, s]
      rw [hnorm, ← pow_mul]
      exact Even.isSquare_pow
        (even_iff_two_dvd.mpr ⟨s.count P.1, rfl⟩) p
    · exact False.elim (hPnonram ⟨p, hp, hcomap, hram.1⟩)
  · intro P hP _hneq
    rw [Finset.mem_filter] at hP
    have hcount : s.count (σ P).1 = s.count P.1 := by
      simpa [σ, s] using normalizedFactors_count_conjAutNormalizedFactor_eq (Qsqrtd (d : ℚ)) hJ P
    have hnorm : Ideal.absNorm (σ P).1 = Ideal.absNorm P.1 := by
      change
        Ideal.absNorm
            (Ideal.map (conjOK : OK →+* OK) P.1) =
          Ideal.absNorm P.1
      exact Ideal.absNorm_map_equiv conjOK P.1
    dsimp [f]
    rw [hcount, hnorm]

/-- An ambiguous ideal whose full ramified parity vector is zero has square
absolute norm. -/
theorem isSquare_absNorm_of_isAmbiguousIdeal_of_forall_fullRamifiedParityVector_eq_zero
    (J : (Ideal OK)⁰)
    (hJ : IsAmbiguousIdeal conjOK (J : Ideal OK))
    (hparity : ∀ p, fullRamifiedParityVector d J p = 0) :
    IsSquare (Ideal.absNorm (J : Ideal OK)) := by
  classical
  let s := UniqueFactorizationMonoid.normalizedFactors (J : Ideal OK)
  let S := s.attach.toFinset
  let f : {P // P ∈ s} → ℕ := fun P => Ideal.absNorm P.1 ^ s.count P.1
  have hJ0 : (J : Ideal OK) ≠ ⊥ := by
    simpa [Ideal.zero_eq_bot] using mem_nonZeroDivisors_iff_ne_zero.mp J.2
  have hnorm : Ideal.absNorm (J : Ideal OK) = ∏ P ∈ S, f P := by
    simpa [S, f, s] using
      Ideal.absNorm_eq_normalizedFactors_absNorm_count_prod (J : Ideal OK) hJ0
  rw [hnorm]
  have hsplit :=
    Finset.prod_filter_mul_prod_filter_not S (fun P => normalizedFactorIsRamified d P) f
  rw [← hsplit]
  exact
    (isSquare_ramified_absNorm_count_prod_of_forall_fullRamifiedParityVector_eq_zero
      d J hparity).mul
    (isSquare_nonramified_absNorm_count_prod_of_isAmbiguousIdeal d J hJ)

end Qsqrtd

end Ambiguous
end ClassGroup
end QuadraticNumberFields
