/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QuadraticNumberFields.ClassGroup.GenusTheory.AmbiguousIdeals.Exact

/-!
# Ambiguous-Ideal Hilbert 90 Outputs

This file records the unit and Hilbert-90 consequences of a generated full
ramified-parity product.
-/

namespace QuadraticNumberFields
namespace ClassGroup
namespace GenusTheory

open scoped nonZeroDivisors NumberField Pointwise QuadraticNumberFields.ClassGroup
open scoped QuadraticNumberFields.Splitting

attribute [-instance] DivisionRing.toRatAlgebra
attribute [local instance] FractionRing.liftAlgebra

namespace Internal

private theorem exists_unit_map_algebraMap_eq_of_toPrincipalIdeal_eq_one
    {R : Type*} [CommRing R] [IsDomain R] {x : (FractionRing R)ˣ}
    (hx : toPrincipalIdeal R (FractionRing R) x = 1) :
    ∃ u : Rˣ, Units.map (algebraMap R (FractionRing R)).toMonoidHom u = x := by
  have hspan : FractionalIdeal.spanSingleton R⁰ (x : FractionRing R) = 1 :=
    (toPrincipalIdeal_eq_iff (I := 1) (x := x)).mp hx
  have hx_mem : (x : FractionRing R) ∈ (1 : FractionalIdeal R⁰ (FractionRing R)) := by
    rw [← hspan]
    exact FractionalIdeal.mem_spanSingleton_self R⁰ (x : FractionRing R)
  have hx_inv : toPrincipalIdeal R (FractionRing R) x⁻¹ = 1 := by
    rw [map_inv, hx, inv_one]
  have hspan_inv :
      FractionalIdeal.spanSingleton R⁰ ((x⁻¹ : (FractionRing R)ˣ) : FractionRing R) = 1 :=
    (toPrincipalIdeal_eq_iff (I := 1) (x := x⁻¹)).mp hx_inv
  have hx_inv_mem :
      ((x⁻¹ : (FractionRing R)ˣ) : FractionRing R) ∈
        (1 : FractionalIdeal R⁰ (FractionRing R)) := by
    rw [← hspan_inv]
    exact FractionalIdeal.mem_spanSingleton_self R⁰
      ((x⁻¹ : (FractionRing R)ˣ) : FractionRing R)
  obtain ⟨a, ha⟩ := (FractionalIdeal.mem_one_iff R⁰).mp hx_mem
  obtain ⟨b, hb⟩ := (FractionalIdeal.mem_one_iff R⁰).mp hx_inv_mem
  refine ⟨
    { val := a
      inv := b
      val_inv := ?_
      inv_val := ?_ }, ?_⟩
  · apply FaithfulSMul.algebraMap_injective R (FractionRing R)
    simp [map_mul, ha, hb]
  · apply FaithfulSMul.algebraMap_injective R (FractionRing R)
    simp [map_mul, ha, hb]
  · apply Units.ext
    simp [ha]

/-- If a full ramified parity product is generated by `γ`, then `σγ / γ` has
trivial principal fractional ideal.

This is the first unit-theoretic output of the kernel generator form: the
ramified parity product is ambiguous, so its generator and conjugate generator
cut out the same principal fractional ideal. The next step is to upgrade this
trivial principal ideal statement to an actual unit/sign datum. -/
theorem toPrincipalIdeal_conjAut_mul_inv_eq_one_of_tp_generator
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    (r : {p // p ∈ ramifiedPrimes d} → Fin 2)
    {γ : (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))ˣ}
    (hγ :
      toPrincipalIdeal (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) γ =
        FractionalIdeal.mk0
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))
          (fullRamifiedParityIdealProduct d r)) :
    toPrincipalIdeal (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
        (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))
        (Units.mapEquiv (conjAutFractionRingAlgEquiv (Qsqrtd (d : ℚ))).toRingEquiv γ *
          γ⁻¹) =
      1 := by
  let R := NumberField.RingOfIntegers (Qsqrtd (d : ℚ))
  let K := Qsqrtd (d : ℚ)
  let I := fullRamifiedParityIdealProduct d r
  have hIamb : IsAmbiguousIdeal (conjAutRingOfIntegers K) (I : Ideal R) := by
    simpa [I, K, R] using isAmbiguousIdeal_fullRamifiedParityIdealProduct d r
  have hIconj : conjAutNonzeroIdealMulEquiv K I = I :=
    (isAmbiguousIdeal_iff_conjAutNonzeroIdealMulEquiv_eq K I).mp hIamb
  have hγ_conj :
      toPrincipalIdeal R (FractionRing R)
          (Units.mapEquiv (conjAutFractionRingAlgEquiv K).toRingEquiv γ) =
        toPrincipalIdeal R (FractionRing R) γ := by
    apply Units.ext
    calc
      ((toPrincipalIdeal R (FractionRing R)
              (Units.mapEquiv (conjAutFractionRingAlgEquiv K).toRingEquiv γ)) :
          FractionalIdeal R⁰ (FractionRing R)) =
          FractionalIdeal.ringEquivMap
            (K := FractionRing R) (L := FractionRing R)
            (conjAutRingOfIntegers K)
            (toPrincipalIdeal R (FractionRing R) γ :
              FractionalIdeal R⁰ (FractionRing R)) := by
        rw [ringEquivMap_conjAut_toPrincipalIdeal]
      _ =
          FractionalIdeal.ringEquivMap
            (K := FractionRing R) (L := FractionRing R)
            (conjAutRingOfIntegers K)
            (FractionalIdeal.mk0 (FractionRing R) I) := by
        rw [hγ]
      _ = FractionalIdeal.mk0 (FractionRing R) (conjAutNonzeroIdealMulEquiv K I) := by
        rw [ringEquivMap_conjAut_mk0]
      _ = FractionalIdeal.mk0 (FractionRing R) I := by
        rw [hIconj]
      _ = (toPrincipalIdeal R (FractionRing R) γ :
          FractionalIdeal R⁰ (FractionRing R)) := by
        rw [hγ]
  rw [map_mul, map_inv, hγ_conj, mul_inv_cancel]

/-- If a full ramified parity product is generated by `γ`, then `σγ / γ` is the
image of an integral unit. -/
theorem exists_unit_map_algebraMap_eq_conjAut_mul_inv_of_tp_generator
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    (r : {p // p ∈ ramifiedPrimes d} → Fin 2)
    {γ : (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))ˣ}
    (hγ :
      toPrincipalIdeal (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) γ =
        FractionalIdeal.mk0
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))
          (fullRamifiedParityIdealProduct d r)) :
    ∃ u : (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))ˣ,
      Units.map
          (algebraMap (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
            (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))).toMonoidHom u =
        Units.mapEquiv (conjAutFractionRingAlgEquiv (Qsqrtd (d : ℚ))).toRingEquiv γ *
          γ⁻¹ := by
  exact exists_unit_map_algebraMap_eq_of_toPrincipalIdeal_eq_one
    (toPrincipalIdeal_conjAut_mul_inv_eq_one_of_tp_generator d r hγ)

private theorem conjAutFractionRingAlgEquiv_apply_apply
    (K : Type*) [Field K] [NumberField K] [Algebra ℚ K]
    [QuadraticField K] [QuadraticField.Conj K]
    (x : FractionRing (NumberField.RingOfIntegers K)) :
    conjAutFractionRingAlgEquiv K (conjAutFractionRingAlgEquiv K x) = x := by
  let R := NumberField.RingOfIntegers K
  have hhom :
      ((conjAutFractionRingAlgEquiv K).toRingHom.comp
          (conjAutFractionRingAlgEquiv K).toRingHom) =
        RingHom.id (FractionRing R) := by
    apply IsFractionRing.ringHom_ext (A := R) (K := FractionRing R)
      (L := FractionRing R)
    intro x
    simp [R, RingHom.comp_apply]
  exact RingHom.congr_fun hhom x

private theorem map_conjAutRingOfIntegers_unit_eq_conjAutFractionRing_map_unit
    (K : Type*) [Field K] [NumberField K] [Algebra ℚ K]
    [QuadraticField K] [QuadraticField.Conj K]
    (u : (NumberField.RingOfIntegers K)ˣ) :
    Units.map
        (algebraMap (NumberField.RingOfIntegers K)
          (FractionRing (NumberField.RingOfIntegers K))).toMonoidHom
        (Units.mapEquiv (conjAutRingOfIntegers K).toMulEquiv u) =
      Units.mapEquiv (conjAutFractionRingAlgEquiv K).toRingEquiv.toMulEquiv
        (Units.map
          (algebraMap (NumberField.RingOfIntegers K)
            (FractionRing (NumberField.RingOfIntegers K))).toMonoidHom u) := by
  apply Units.ext
  simp

/-- If an integral unit maps to `σγ / γ`, then it has quadratic norm one:
`σu * u = 1`. This is the unit-theoretic shape needed before applying the
Hilbert-90/sign analysis. -/
theorem conjAutRingOfIntegers_unit_mul_self_eq_one_of_map_eq_conjAut_mul_inv
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    {γ : (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))ˣ}
    {u : (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))ˣ}
    (hu :
      Units.map
          (algebraMap (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
            (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))).toMonoidHom u =
        Units.mapEquiv (conjAutFractionRingAlgEquiv (Qsqrtd (d : ℚ))).toRingEquiv γ *
          γ⁻¹) :
    Units.mapEquiv (conjAutRingOfIntegers (Qsqrtd (d : ℚ))).toMulEquiv u * u = 1 := by
  let R := NumberField.RingOfIntegers (Qsqrtd (d : ℚ))
  let K := Qsqrtd (d : ℚ)
  let σF := Units.mapEquiv (conjAutFractionRingAlgEquiv K).toRingEquiv.toMulEquiv
  let algUnits : Rˣ →* (FractionRing R)ˣ :=
    Units.map (algebraMap R (FractionRing R)).toMonoidHom
  have hσhu : σF (algUnits u) = γ * (σF γ)⁻¹ := by
    rw [hu]
    apply Units.ext
    simp [σF, K, conjAutFractionRingAlgEquiv_apply_apply]
  have hmap :
      algUnits (Units.mapEquiv (conjAutRingOfIntegers K).toMulEquiv u * u) = 1 := by
    rw [map_mul]
    rw [map_conjAutRingOfIntegers_unit_eq_conjAutFractionRing_map_unit]
    rw [hσhu, hu]
    change γ * (σF γ)⁻¹ * (σF γ * γ⁻¹) = 1
    calc
      γ * (σF γ)⁻¹ * (σF γ * γ⁻¹) = γ * ((σF γ)⁻¹ * σF γ) * γ⁻¹ := by
        ac_rfl
      _ = γ * 1 * γ⁻¹ := by
        rw [inv_mul_cancel]
      _ = 1 := by
        rw [mul_one, mul_inv_cancel]
  apply Units.ext
  apply FaithfulSMul.algebraMap_injective R (FractionRing R)
  simpa [algUnits, R, K] using Units.ext_iff.mp hmap

/-- For a generator of a full ramified parity product, the integral unit
representing `σγ / γ` may be chosen with quadratic norm one. -/
theorem exists_normOne_unit_map_algebraMap_eq_conjAut_mul_inv_of_tp_generator
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    (r : {p // p ∈ ramifiedPrimes d} → Fin 2)
    {γ : (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))ˣ}
    (hγ :
      toPrincipalIdeal (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) γ =
        FractionalIdeal.mk0
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))
          (fullRamifiedParityIdealProduct d r)) :
    ∃ u : (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))ˣ,
      Units.map
          (algebraMap (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
            (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))).toMonoidHom u =
          Units.mapEquiv (conjAutFractionRingAlgEquiv (Qsqrtd (d : ℚ))).toRingEquiv γ *
            γ⁻¹ ∧
        Units.mapEquiv (conjAutRingOfIntegers (Qsqrtd (d : ℚ))).toMulEquiv u * u = 1 := by
  obtain ⟨u, hu⟩ := exists_unit_map_algebraMap_eq_conjAut_mul_inv_of_tp_generator d r hγ
  exact ⟨u, hu, conjAutRingOfIntegers_unit_mul_self_eq_one_of_map_eq_conjAut_mul_inv d hu⟩

/-- The equation `σu * u = 1` on an integral unit says that the corresponding
field element has algebraic norm one. -/
theorem algebra_norm_eq_one_of_conjAutRingOfIntegers_unit_mul_self_eq_one
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    {u : (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))ˣ}
    (hu :
      Units.mapEquiv (conjAutRingOfIntegers (Qsqrtd (d : ℚ))).toMulEquiv u * u = 1) :
    Algebra.norm ℚ ((u : NumberField.RingOfIntegers (Qsqrtd (d : ℚ))) :
      Qsqrtd (d : ℚ)) = 1 := by
  let R := NumberField.RingOfIntegers (Qsqrtd (d : ℚ))
  let K := Qsqrtd (d : ℚ)
  have hR :
      (conjAutRingOfIntegers K (u : R)) * (u : R) = 1 := by
    simpa [R, K] using Units.ext_iff.mp hu
  have hK :
      QuadraticField.conjAut K ((u : R) : K) * ((u : R) : K) = 1 := by
    simpa [R, K, map_mul, coe_conjAutRingOfIntegers_apply] using
      congrArg (fun x : R => (x : K)) hR
  apply FaithfulSMul.algebraMap_injective ℚ K
  calc
    algebraMap ℚ K (Algebra.norm ℚ ((u : R) : K)) =
        ((u : R) : K) * QuadraticField.conjAut K ((u : R) : K) := by
      rw [← QuadraticField.mul_conj_eq_norm_image]
    _ = QuadraticField.conjAut K ((u : R) : K) * ((u : R) : K) := by
      rw [mul_comm]
    _ = 1 := hK

/-- A norm-one integral unit obtained from the generator relation is a Hilbert
90 coboundary in the ring of integers. -/
theorem exists_hilbert90_coboundary_of_conjAutRingOfIntegers_unit_mul_self_eq_one
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    {u : (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))ˣ}
    (hu :
      Units.mapEquiv (conjAutRingOfIntegers (Qsqrtd (d : ℚ))).toMulEquiv u * u = 1) :
    ∃ ε : NumberField.RingOfIntegers (Qsqrtd (d : ℚ)), ε ≠ 0 ∧
      (u : NumberField.RingOfIntegers (Qsqrtd (d : ℚ))) *
          conjAutRingOfIntegers (Qsqrtd (d : ℚ)) ε = ε := by
  exact exists_mul_conjAutRingOfIntegers_eq_self_of_norm_eq_one (Qsqrtd (d : ℚ))
    (algebra_norm_eq_one_of_conjAutRingOfIntegers_unit_mul_self_eq_one d hu)

/-- For a generator of a full ramified parity product, the associated integral
unit admits a Hilbert-90 coboundary representative. -/
theorem exists_hilbert90_coboundary_unit_of_tp_generator
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    (r : {p // p ∈ ramifiedPrimes d} → Fin 2)
    {γ : (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))ˣ}
    (hγ :
      toPrincipalIdeal (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) γ =
        FractionalIdeal.mk0
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))
          (fullRamifiedParityIdealProduct d r)) :
    ∃ u : (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))ˣ,
      Units.map
          (algebraMap (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
            (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))).toMonoidHom u =
          Units.mapEquiv (conjAutFractionRingAlgEquiv (Qsqrtd (d : ℚ))).toRingEquiv γ *
            γ⁻¹ ∧
        ∃ ε : NumberField.RingOfIntegers (Qsqrtd (d : ℚ)), ε ≠ 0 ∧
          (u : NumberField.RingOfIntegers (Qsqrtd (d : ℚ))) *
              conjAutRingOfIntegers (Qsqrtd (d : ℚ)) ε = ε := by
  obtain ⟨u, hu, hnorm⟩ :=
    exists_normOne_unit_map_algebraMap_eq_conjAut_mul_inv_of_tp_generator d r hγ
  exact ⟨u, hu, exists_hilbert90_coboundary_of_conjAutRingOfIntegers_unit_mul_self_eq_one
    d hnorm⟩

/-- Combining `algebraMap u = σγ / γ` with the Hilbert-90 equation
`u * σε = ε` makes `γ * ε` fixed by fraction-field conjugation. -/
theorem conjAutFractionRingAlgEquiv_mul_algebraMap_eq_self_of_hilbert90_coboundary
    (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]
    {γ : (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))ˣ}
    {u : (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))ˣ}
    {ε : NumberField.RingOfIntegers (Qsqrtd (d : ℚ))}
    (hu :
      Units.map
          (algebraMap (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
            (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ))))).toMonoidHom u =
        Units.mapEquiv (conjAutFractionRingAlgEquiv (Qsqrtd (d : ℚ))).toRingEquiv γ *
          γ⁻¹)
    (hε :
      (u : NumberField.RingOfIntegers (Qsqrtd (d : ℚ))) *
          conjAutRingOfIntegers (Qsqrtd (d : ℚ)) ε = ε) :
    conjAutFractionRingAlgEquiv (Qsqrtd (d : ℚ))
        ((γ : FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) *
          algebraMap (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
            (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) ε) =
      (γ : FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) *
        algebraMap (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))
          (FractionRing (NumberField.RingOfIntegers (Qsqrtd (d : ℚ)))) ε := by
  let R := NumberField.RingOfIntegers (Qsqrtd (d : ℚ))
  let K := Qsqrtd (d : ℚ)
  let F := FractionRing R
  let σ := conjAutFractionRingAlgEquiv K
  let σU := Units.mapEquiv σ.toRingEquiv.toMulEquiv
  let E : F := algebraMap R F ε
  have huval :
      algebraMap R F (u : R) = (σU γ : F) * ((γ⁻¹ : Fˣ) : F) := by
    simpa [R, K, F, σ, σU] using congrArg Units.val hu
  have hεmap :
      algebraMap R F (u : R) * σ E = E := by
    simpa [R, K, F, σ, E, map_mul, conjAutFractionRingAlgEquiv_algebraMap] using
      congrArg (fun x : R => algebraMap R F x) hε
  have hkey : ((σU γ : F) * ((γ⁻¹ : Fˣ) : F)) * σ E = E := by
    rw [← huval]
    exact hεmap
  have hγinv : (γ : F) * ((γ⁻¹ : Fˣ) : F) = 1 := by
    simp
  calc
    σ ((γ : F) * E) = (σU γ : F) * σ E := by
      simp [σU]
    _ = ((γ : F) * ((γ⁻¹ : Fˣ) : F)) * ((σU γ : F) * σ E) := by
      rw [hγinv, one_mul]
    _ = (γ : F) * (((σU γ : F) * ((γ⁻¹ : Fˣ) : F)) * σ E) := by
      ring
    _ = (γ : F) * E := by
      rw [hkey]

end Internal

end GenusTheory
end ClassGroup
end QuadraticNumberFields
