/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import Mathlib.Algebra.CharP.CharAndCard
import Mathlib.RingTheory.Ideal.Norm.AbsNorm
import Mathlib.RingTheory.Ideal.Quotient.Operations
import QNFMathlib.RingTheory.Ideal.Span

/-!
# Ideal Absolute Norm Lemmas

Material destined for mathlib.
-/

namespace Ideal

/-- The absolute norm of an ideal is invariant under a ring equivalence. -/
theorem absNorm_map_equiv
    {R S : Type*} [CommRing R] [CommRing S]
    [Nontrivial R] [Nontrivial S]
    [IsDedekindDomain R] [IsDedekindDomain S]
    [Module.Free ℤ R] [Module.Free ℤ S]
    (e : R ≃+* S) (I : Ideal R) :
    Ideal.absNorm (I.map (e : R →+* S)) = Ideal.absNorm I := by
  rw [Ideal.absNorm_apply, Ideal.absNorm_apply]
  exact Nat.card_congr (Ideal.quotientEquiv I (I.map (e : R →+* S)) e rfl).symm.toEquiv

/-- A nonzero prime ideal of a finite free `ℤ`-algebra lies over a rational prime
that divides its absolute norm. -/
theorem exists_nat_prime_comap_eq_span_and_dvd_absNorm_of_isPrime
    {R : Type*} [CommRing R] [Algebra ℤ R] [IsDedekindDomain R]
    [Module.Free ℤ R] [Module.Finite ℤ R]
    {P : Ideal R} (hP : P.IsPrime) (hP0 : P ≠ ⊥) :
    ∃ p : ℕ, p.Prime ∧
      Ideal.comap (algebraMap ℤ R) P = Ideal.span ({(p : ℤ)} : Set ℤ) ∧
        p ∣ Ideal.absNorm P := by
  have habs0 : Ideal.absNorm P ≠ 0 := by
    rwa [Ne, Ideal.absNorm_eq_zero_iff]
  obtain ⟨q, hq⟩ := (IsPrincipalIdealRing.principal
    (Ideal.comap (algebraMap ℤ R) P)).principal
  rw [Ideal.submodule_span_eq] at hq
  have hmem : ((Ideal.absNorm P : ℤ)) ∈ Ideal.comap (algebraMap ℤ R) P := by
    simpa using Ideal.absNorm_mem P
  have hq0 : q ≠ 0 := by
    rintro rfl
    exact habs0 (by simpa [hq] using hmem)
  have hqprime : Prime q := by
    rw [← Ideal.span_singleton_prime hq0, ← hq]
    exact hP.comap _
  have hp : q.natAbs.Prime := Int.prime_iff_natAbs_prime.mp hqprime
  have hspan : Ideal.span ({(q.natAbs : ℤ)} : Set ℤ) = Ideal.span ({q} : Set ℤ) :=
    Ideal.span_singleton_eq_span_singleton.mpr (Int.associated_natAbs q).symm
  have hpP : (q.natAbs : ℤ) ∣ (Ideal.absNorm P : ℤ) := by
    rw [← Ideal.mem_span_singleton, hspan, ← hq]
    exact hmem
  exact ⟨q.natAbs, hp, hq.trans hspan.symm, by exact_mod_cast hpP⟩

/-- If a nonzero ideal is coprime to the ideal generated by a rational prime `p`,
then its absolute norm is coprime to `p`.

The proof works by reducing to the finite quotient `R ⧸ I`: coprimality of the
ideals makes `p` a unit in the quotient, while `p ∣ absNorm I` would force `p`
to divide the quotient cardinality, contradicting
`not_isUnit_prime_of_dvd_card`. -/
theorem absNorm_coprime_prime_of_isCoprime_span_natCast
    {R : Type*} [CommRing R] [Nontrivial R] [IsDedekindDomain R]
    [Module.Free ℤ R] [Module.Finite ℤ R]
    (I : Ideal R) (p : ℕ) [Fact p.Prime]
    (hI_ne : I ≠ ⊥)
    (hcop : IsCoprime I (Ideal.span ({(p : R)} : Set R))) :
    (Ideal.absNorm I).Coprime p := by
  rw [Nat.coprime_comm]
  refine (Fact.out : Nat.Prime p).coprime_iff_not_dvd.mpr ?_
  intro hp_dvd
  have hnorm_ne : Ideal.absNorm I ≠ 0 := by
    intro hnorm
    exact hI_ne (Ideal.absNorm_eq_zero_iff.mp hnorm)
  have hfinite : Finite (R ⧸ I) := (Ideal.absNorm_ne_zero_iff I).mp hnorm_ne
  letI : Fintype (R ⧸ I) := Fintype.ofFinite _
  have hp_card : p ∣ Fintype.card (R ⧸ I) := by
    simpa [Ideal.absNorm_apply, Submodule.cardQuot_apply] using hp_dvd
  have hp_unit : IsUnit ((p : ℕ) : R ⧸ I) := by
    have hone : (1 : R) ∈ I ⊔ Ideal.span ({(p : R)} : Set R) := by
      rw [Ideal.isCoprime_iff_sup_eq.mp hcop]
      trivial
    rcases Submodule.mem_sup.mp hone with ⟨i, hi, s, hs, his⟩
    rw [Ideal.mem_span_singleton] at hs
    rcases hs with ⟨a, ha⟩
    refine isUnit_iff_exists_inv.mpr ⟨Ideal.Quotient.mk I a, ?_⟩
    rw [← map_natCast (Ideal.Quotient.mk I), ← map_mul]
    rw [← ha]
    have hsum_q := congrArg (Ideal.Quotient.mk I) his
    have hi_zero : Ideal.Quotient.mk I i = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr hi
    simpa [map_add, hi_zero] using hsum_q
  exact not_isUnit_prime_of_dvd_card hp_card hp_unit

/-- If a nonzero ideal is coprime to the ideal generated by a natural number `n`,
then its absolute norm is coprime to `n`. -/
theorem absNorm_coprime_of_isCoprime_span_natCast
    {R : Type*} [CommRing R] [Nontrivial R] [IsDedekindDomain R]
    [Module.Free ℤ R] [Module.Finite ℤ R]
    (I : Ideal R) (n : ℕ)
    (hI_ne : I ≠ ⊥)
    (hcop : IsCoprime I (Ideal.span ({(n : R)} : Set R))) :
    (Ideal.absNorm I).Coprime n := by
  refine Nat.coprime_of_dvd ?_
  intro q hq hq_abs hq_n
  haveI : Fact q.Prime := ⟨hq⟩
  have hcopq : IsCoprime I (Ideal.span ({(q : R)} : Set R)) :=
    isCoprime_span_natCast_of_isCoprime_span_natCast_of_dvd I hcop hq_n
  have hq_coprime : (Ideal.absNorm I).Coprime q :=
    absNorm_coprime_prime_of_isCoprime_span_natCast I q hI_ne hcopq
  exact ((Nat.Prime.coprime_iff_not_dvd hq).mp (Nat.coprime_comm.mp hq_coprime)) hq_abs

/-- If a nonzero ideal and the ideal generated by a natural number `n` span the
unit ideal, then the ideal's absolute norm is coprime to `n`. -/
theorem absNorm_coprime_of_sup_span_natCast_eq_top
    {R : Type*} [CommRing R] [Nontrivial R] [IsDedekindDomain R]
    [Module.Free ℤ R] [Module.Finite ℤ R]
    (I : Ideal R) (n : ℕ)
    (hI_ne : I ≠ ⊥)
    (hcop : I ⊔ Ideal.span ({(n : R)} : Set R) = ⊤) :
    (Ideal.absNorm I).Coprime n :=
  absNorm_coprime_of_isCoprime_span_natCast I n hI_ne
    (Ideal.isCoprime_iff_sup_eq.mpr hcop)

/-- If a nonzero ideal and the ideal generated by a rational prime `p` span the
unit ideal, then the ideal's absolute norm is coprime to `p`. -/
theorem absNorm_coprime_prime_of_sup_span_natCast_eq_top
    {R : Type*} [CommRing R] [Nontrivial R] [IsDedekindDomain R]
    [Module.Free ℤ R] [Module.Finite ℤ R]
    (I : Ideal R) (p : ℕ) [Fact p.Prime]
    (hI_ne : I ≠ ⊥)
    (hcop : I ⊔ Ideal.span ({(p : R)} : Set R) = ⊤) :
    (Ideal.absNorm I).Coprime p :=
  absNorm_coprime_of_sup_span_natCast_eq_top I p hI_ne hcop

end Ideal
