/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import Mathlib.Algebra.CharP.CharAndCard
import Mathlib.RingTheory.Ideal.Norm.AbsNorm
import Mathlib.RingTheory.Ideal.Quotient.Operations
import QNFMathlib.RingTheory.Ideal.Span

/-!
# Ideal Absolute Norm Lemmas

Material destined for mathlib.
-/

namespace Ideal

section RingEquiv

variable {R : Type*} [CommRing R] [Nontrivial R] [IsDedekindDomain R] [Module.Free ℤ R]

/-- Absolute norm is invariant under a ring equivalence. -/
theorem absNorm_map_equiv (σ : R ≃+* R) (I : Ideal R) :
    Ideal.absNorm (Ideal.map (σ : R →+* R) I) = Ideal.absNorm I := by
  rw [Ideal.absNorm_apply, Ideal.absNorm_apply, Submodule.cardQuot_apply,
    Submodule.cardQuot_apply]
  exact Nat.card_congr
    (Ideal.quotientEquiv I (Ideal.map (σ : R →+* R) I) σ rfl).toEquiv.symm

end RingEquiv

section PrimeComap

variable {R : Type*} [CommRing R] [Algebra ℤ R] [IsDedekindDomain R]
variable [Module.Free ℤ R] [Module.Finite ℤ R]

/-- A nonzero prime ideal of a finite free `ℤ`-algebra lies over a rational prime
that divides its absolute norm. -/
theorem exists_nat_prime_comap_eq_span_and_dvd_absNorm_of_isPrime
    {P : Ideal R} (hP : P.IsPrime) (hP0 : P ≠ ⊥) :
    ∃ p : ℕ, p.Prime ∧
      Ideal.comap (algebraMap ℤ R) P = Ideal.span ({(p : ℤ)} : Set ℤ) ∧
        p ∣ Ideal.absNorm P := by
  have habs0 : Ideal.absNorm P ≠ 0 := by
    rwa [Ne, Ideal.absNorm_eq_zero_iff]
  obtain ⟨q, hq⟩ := (IsPrincipalIdealRing.principal
    (Ideal.comap (algebraMap ℤ R) P)).principal
  rw [Ideal.submodule_span_eq] at hq
  have hmem : ((Ideal.absNorm P : ℤ)) ∈ Ideal.comap (algebraMap ℤ R) P := by
    simpa using Ideal.absNorm_mem P
  have hq0 : q ≠ 0 := by
    rintro rfl
    rw [hq, Ideal.span_singleton_eq_bot.mpr rfl, Ideal.mem_bot, Nat.cast_eq_zero] at hmem
    exact habs0 hmem
  have hqprime : Prime q := by
    rw [← Ideal.span_singleton_prime hq0, ← hq]
    exact hP.comap _
  have hp : q.natAbs.Prime := Int.prime_iff_natAbs_prime.mp hqprime
  have hspan : Ideal.span ({(q.natAbs : ℤ)} : Set ℤ) = Ideal.span ({q} : Set ℤ) :=
    Ideal.span_singleton_eq_span_singleton.mpr (Int.associated_natAbs q).symm
  have hpP : (q.natAbs : ℤ) ∣ (Ideal.absNorm P : ℤ) := by
    rw [← Ideal.mem_span_singleton, hspan, ← hq]
    exact hmem
  exact ⟨q.natAbs, hp, hq.trans hspan.symm, by exact_mod_cast hpP⟩

end PrimeComap

section Coprime

variable {R : Type*} [CommRing R] [Nontrivial R] [IsDedekindDomain R]
variable [Module.Free ℤ R] [Module.Finite ℤ R]

/-- If a nonzero ideal is coprime to the ideal generated by a rational prime `p`,
then its absolute norm is coprime to `p`.

The proof works by reducing to the finite quotient `R ⧸ I`: coprimality of the
ideals makes `p` a unit in the quotient, while `p ∣ absNorm I` would force `p`
to divide the quotient cardinality, contradicting
`not_isUnit_prime_of_dvd_card`. -/
theorem absNorm_coprime_prime_of_isCoprime_span_natCast
    (I : Ideal R) (p : ℕ) [Fact p.Prime]
    (hI_ne : I ≠ ⊥)
    (hcop : IsCoprime I (Ideal.span ({(p : R)} : Set R))) :
    (Ideal.absNorm I).Coprime p := by
  rw [Nat.coprime_comm]
  refine (Fact.out : Nat.Prime p).coprime_iff_not_dvd.mpr ?_
  intro hp_dvd
  have hnorm_ne : Ideal.absNorm I ≠ 0 := by
    intro hnorm
    exact hI_ne (Ideal.absNorm_eq_zero_iff.mp hnorm)
  have hfinite : Finite (R ⧸ I) := (Ideal.absNorm_ne_zero_iff I).mp hnorm_ne
  letI : Fintype (R ⧸ I) := Fintype.ofFinite _
  have hp_card : p ∣ Fintype.card (R ⧸ I) := by
    rw [Ideal.absNorm_apply, Submodule.cardQuot_apply] at hp_dvd
    rwa [Nat.card_eq_fintype_card] at hp_dvd
  have hp_unit : IsUnit ((p : ℕ) : R ⧸ I) := by
    have hone : (1 : R) ∈ I ⊔ Ideal.span ({(p : R)} : Set R) := by
      rw [Ideal.isCoprime_iff_sup_eq.mp hcop]
      trivial
    rcases Submodule.mem_sup.mp hone with ⟨i, hi, s, hs, his⟩
    rw [Ideal.mem_span_singleton] at hs
    rcases hs with ⟨a, ha⟩
    refine isUnit_iff_exists_inv.mpr ⟨Ideal.Quotient.mk I a, ?_⟩
    rw [← map_natCast (Ideal.Quotient.mk I), ← map_mul]
    rw [← ha]
    have hsum_q := congrArg (Ideal.Quotient.mk I) his
    have hi_zero : Ideal.Quotient.mk I i = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr hi
    simpa [map_add, hi_zero] using hsum_q
  exact not_isUnit_prime_of_dvd_card hp_card hp_unit

/-- If a nonzero ideal is coprime to the ideal generated by a natural number `n`,
then its absolute norm is coprime to `n`. -/
theorem absNorm_coprime_of_isCoprime_span_natCast
    (I : Ideal R) (n : ℕ)
    (hI_ne : I ≠ ⊥)
    (hcop : IsCoprime I (Ideal.span ({(n : R)} : Set R))) :
    (Ideal.absNorm I).Coprime n := by
  refine Nat.coprime_of_dvd ?_
  intro q hq hq_abs hq_n
  haveI : Fact q.Prime := ⟨hq⟩
  have hcopq : IsCoprime I (Ideal.span ({(q : R)} : Set R)) :=
    isCoprime_span_natCast_of_isCoprime_span_natCast_of_dvd I hcop hq_n
  have hq_coprime : (Ideal.absNorm I).Coprime q :=
    absNorm_coprime_prime_of_isCoprime_span_natCast I q hI_ne hcopq
  exact ((Nat.Prime.coprime_iff_not_dvd hq).mp (Nat.coprime_comm.mp hq_coprime)) hq_abs

/-- If a nonzero ideal and the ideal generated by a natural number `n` span the
unit ideal, then the ideal's absolute norm is coprime to `n`. -/
theorem absNorm_coprime_of_sup_span_natCast_eq_top
    (I : Ideal R) (n : ℕ)
    (hI_ne : I ≠ ⊥)
    (hcop : I ⊔ Ideal.span ({(n : R)} : Set R) = ⊤) :
    (Ideal.absNorm I).Coprime n :=
  absNorm_coprime_of_isCoprime_span_natCast I n hI_ne
    (Ideal.isCoprime_iff_sup_eq.mpr hcop)

/-- If a nonzero ideal and the ideal generated by a rational prime `p` span the
unit ideal, then the ideal's absolute norm is coprime to `p`. -/
theorem absNorm_coprime_prime_of_sup_span_natCast_eq_top
    (I : Ideal R) (p : ℕ) [Fact p.Prime]
    (hI_ne : I ≠ ⊥)
    (hcop : I ⊔ Ideal.span ({(p : R)} : Set R) = ⊤) :
    (Ideal.absNorm I).Coprime p :=
  absNorm_coprime_of_sup_span_natCast_eq_top I p hI_ne hcop

end Coprime

section NormalizedFactorProducts

variable {R : Type*} [CommRing R] [Nontrivial R] [IsDedekindDomain R] [Module.Free ℤ R]

private theorem pow_dvd_multiset_prod_of_le_count
    {M : Type*} [CommMonoid M] [DecidableEq M]
    (s : Multiset M) (a : M) {n : ℕ} (h : n ≤ s.count a) :
    a ^ n ∣ s.prod := by
  have hrep : Multiset.replicate n a ≤ s :=
    (Multiset.le_count_iff_replicate_le).mp h
  have hdiv := Multiset.prod_dvd_prod_of_le hrep
  simpa [Multiset.prod_replicate] using hdiv

/-- If a prime ideal occurs at least twice in the normalized factorization of
`I`, then the square of its absolute norm divides `Ideal.absNorm I`. -/
theorem absNorm_sq_dvd_of_two_le_normalizedFactors_count
    {I P : Ideal R} (hI : I ≠ ⊥)
    (hcount : 2 ≤ (UniqueFactorizationMonoid.normalizedFactors I).count P) :
    Ideal.absNorm P ^ 2 ∣ Ideal.absNorm I := by
  have hP2_dvd : P ^ 2 ∣ I := by
    have h := pow_dvd_multiset_prod_of_le_count
      (UniqueFactorizationMonoid.normalizedFactors I) P hcount
    rwa [Ideal.prod_normalizedFactors_eq_self hI] at h
  have hnorm := map_dvd Ideal.absNorm hP2_dvd
  simpa using hnorm

private theorem finset_prod_multiset_attach_toFinset_count
    {α M : Type*} [DecidableEq α] [CommMonoid M]
    (s : Multiset α) (f : α → M) :
    (∏ P ∈ s.attach.toFinset, f P.1 ^ s.count P.1) =
      ∏ P ∈ s.toFinset, f P ^ s.count P := by
  classical
  refine Finset.prod_bij (fun P _hP ↦ P.1) ?_ ?_ ?_ ?_
  · intro P _hP
    exact Multiset.mem_toFinset.mpr P.2
  · intro P _hP Q _hQ hPQ
    exact Subtype.ext hPQ
  · intro P hP
    refine ⟨⟨P, Multiset.mem_toFinset.mp hP⟩, ?_, rfl⟩
    simp
  · intro P _hP
    rfl

/-- The absolute norm of a nonzero ideal is the product of the absolute norms
of its normalized prime factors, counted with multiplicity. -/
theorem absNorm_eq_normalizedFactors_absNorm_count_prod
    (I : Ideal R) (hI0 : I ≠ ⊥) :
    Ideal.absNorm I =
      ∏ P ∈ (UniqueFactorizationMonoid.normalizedFactors I).attach.toFinset,
        Ideal.absNorm P.1 ^
          (UniqueFactorizationMonoid.normalizedFactors I).count P.1 := by
  let s := UniqueFactorizationMonoid.normalizedFactors I
  calc
    Ideal.absNorm I = Ideal.absNorm s.prod := by
      rw [Ideal.prod_normalizedFactors_eq_self hI0]
    _ = (s.map fun P ↦ Ideal.absNorm P).prod := by
      rw [map_multiset_prod]
    _ = ∏ P ∈ s.attach.toFinset, Ideal.absNorm P.1 ^ s.count P.1 := by
      simpa [finset_prod_multiset_attach_toFinset_count] using
        Finset.prod_multiset_map_count s (fun P ↦ Ideal.absNorm P)

end NormalizedFactorProducts

section NormalizedFactors

variable {R : Type*} [CommRing R] [Nontrivial R] [Algebra ℤ R] [IsDedekindDomain R]
variable [Module.Free ℤ R] [Module.Finite ℤ R]

/-- If a rational prime divides the absolute norm of a nonzero ideal in a
finite free `ℤ`-Dedekind algebra, then some normalized prime factor of the ideal
lies over `(p)`. -/
theorem exists_normalizedFactor_mem_primesOver_of_nat_prime_dvd_absNorm
    {I : Ideal R} (hI0 : I ≠ ⊥) {p : ℕ} (hp : p.Prime)
    (hpdiv : p ∣ Ideal.absNorm I) :
    ∃ P : Ideal R,
      P ∈ UniqueFactorizationMonoid.normalizedFactors I ∧
        P ∈ Ideal.primesOver (Ideal.span ({(p : ℤ)} : Set ℤ)) R := by
  letI : Fact p.Prime := ⟨hp⟩
  have hnot_sup : I ⊔ Ideal.span ({(p : R)} : Set R) ≠ ⊤ := by
    intro htop
    have hcop : (Ideal.absNorm I).Coprime p :=
      Ideal.absNorm_coprime_prime_of_sup_span_natCast_eq_top I p hI0 htop
    have hcop' : p.Coprime (Ideal.absNorm I) := Nat.coprime_comm.mp hcop
    exact ((Nat.Prime.coprime_iff_not_dvd hp).mp hcop') hpdiv
  obtain ⟨M, hMmax, hsupM⟩ :=
    Ideal.exists_le_maximal (I ⊔ Ideal.span ({(p : R)} : Set R)) hnot_sup
  have hIle : I ≤ M := le_sup_left.trans hsupM
  have hpSpan_le : Ideal.span ({(p : R)} : Set R) ≤ M := le_sup_right.trans hsupM
  have hmap :
      Ideal.map (algebraMap ℤ R) (Ideal.span ({(p : ℤ)} : Set ℤ)) =
        Ideal.span ({(p : R)} : Set R) := by
    rw [Ideal.map_span, Set.image_singleton]
    simp
  have hlecomap :
      (Ideal.span ({(p : ℤ)} : Set ℤ)) ≤ M.comap (algebraMap ℤ R) := by
    rw [← Ideal.map_le_iff_le_comap, hmap]
    exact hpSpan_le
  have hcomap_ne_top : M.comap (algebraMap ℤ R) ≠ ⊤ := by
    intro htop
    apply hMmax.ne_top
    rw [Ideal.eq_top_iff_one]
    have hone : (1 : ℤ) ∈ M.comap (algebraMap ℤ R) := by
      rw [htop]
      trivial
    simpa using hone
  haveI : (Ideal.span ({(p : ℤ)} : Set ℤ)).IsMaximal :=
    PrincipalIdealRing.isMaximal_of_irreducible
      ((Nat.prime_iff_prime_int.mp hp).irreducible)
  have hcomap : M.comap (algebraMap ℤ R) =
      Ideal.span ({(p : ℤ)} : Set ℤ) := by
    exact (show (Ideal.span ({(p : ℤ)} : Set ℤ)).IsMaximal from inferInstance).eq_of_le
      hcomap_ne_top hlecomap |>.symm
  refine ⟨M, ?_, ?_⟩
  · exact (Ideal.mem_normalizedFactors_iff hI0).mpr ⟨hMmax.isPrime, hIle⟩
  · exact ⟨hMmax.isPrime, ⟨hcomap.symm⟩⟩

end NormalizedFactors

end Ideal
