/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import QuadraticNumberFields.RingOfIntegers.CommonInstances
import QuadraticNumberFields.Examples.SqrtNeg5.ClassNumber
import QuadraticNumberFields.Forms.Structure
import QuadraticNumberFields.Forms.Enumeration
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# √-5: Form class group — full theory tour

This file walks through the complete theory chain for `ℚ(√-5)` (the classic
non-UFD quadratic field with class number two).  Each section exercises a
different layer of the project.

## Sections

1. **Invariants** — field discriminant, Minkowski bound
2. **Reduced forms** — enumerate the two reduced BQFs of discriminant -20
3. **Class number** — `classNumberQsqrtd (-5) = 2` via both ideal and form methods
4. **Form class group structure** — transported `CommGroup` + Cox multiplicative property
5. **Cox equivalence** — bijection cardinality, non-identity classP
6. **Group law** — `classP² = 1`, the group is `ℤ/2ℤ`, transported to form classes

All lemmas are sorry-free.
-/

set_option linter.style.nativeDecide false

open scoped NumberField

attribute [-instance] DivisionRing.toRatAlgebra

noncomputable section

namespace QuadraticNumberFields
namespace Examples
namespace SqrtNeg5

open QuadraticNumberFields.BinaryQuadraticForm

/-! ## 1. Invariants -/

section Invariants

/-- `ℚ(√-5)` has ring of integers `ℤ[√-5]` (`-5 ≡ 3 mod 4` branch). -/
example : (-5 : ℤ) % 4 ≠ 1 := by decide

/-- The field discriminant of `ℚ(√-5)` is `-20`. -/
example : fieldDiscriminant (-5 : ℤ) = -20 := by
  have hd4 : (-5 : ℤ) % 4 ≠ 1 := by decide
  rw [fieldDiscriminant_of_mod_four_ne_one hd4]
  ring

/-- The Minkowski bound for `ℚ(√-5)` is less than 3, so the class group is
generated by ideals of norm ≤ 2. -/
example : Qsqrtd.minkowskiBound (-5 : ℤ) < 3 :=
  minkowskiBound_lt_three

end Invariants

/-! ## 2. Reduced forms of discriminant -20 -/

section ReducedForms

/-- There are exactly two primitive reduced positive definite forms of the field
discriminant `-20`. -/
example : (enumPrimitiveReducedForms (fieldDiscriminant (-5 : ℤ))).card = 2 := by
  have hd4 : (-5 : ℤ) % 4 ≠ 1 := by decide
  rw [fieldDiscriminant_of_mod_four_ne_one hd4]
  native_decide

/-- The principal form `x² + 5y²` is primitive, positive definite, reduced,
and has discriminant -20. -/
example : (BinaryQuadraticForm.mk 1 0 5).disc = -20 := by
  native_decide

example : (BinaryQuadraticForm.mk 1 0 5).IsPrimitive := by
  native_decide

example : (BinaryQuadraticForm.mk 1 0 5).IsPositiveDefinite := by
  native_decide

example : (BinaryQuadraticForm.mk 1 0 5).IsReduced := by
  native_decide

/-- The non-principal reduced form is `2x² + 2xy + 3y²`. -/
example : (BinaryQuadraticForm.mk 2 2 3).disc = -20 := by
  native_decide

example : (BinaryQuadraticForm.mk 2 2 3).IsPrimitive := by
  native_decide

example : (BinaryQuadraticForm.mk 2 2 3).IsPositiveDefinite := by
  native_decide

example : (BinaryQuadraticForm.mk 2 2 3).IsReduced := by
  native_decide

/-- The two reduced forms are distinct. -/
example : (BinaryQuadraticForm.mk 1 0 5) ≠ (BinaryQuadraticForm.mk 2 2 3) := by
  native_decide

end ReducedForms

/-! ## 3. Class number via reduced forms -/

section ClassNumber

/-- `ℚ(√-5)` has class number two — the classic non-UFD example. -/
example : classNumberQsqrtd (-5 : ℤ) = 2 :=
  classNumberQsqrtd_neg5

/-- The class number equals the count of primitive reduced positive definite
forms of the field discriminant.  This is the bridge between ideal-class and
form-class viewpoints. -/
example : classNumberQsqrtd (-5 : ℤ) =
    (enumPrimitiveReducedForms (fieldDiscriminant (-5 : ℤ))).card :=
  classNumberQsqrtd_eq_reducedForms_card (-5 : ℤ) (by decide : (-5 : ℤ) < 0)

end ClassNumber

/-! ## 4. Form class group structure — transported `CommGroup` -/

section FormClassGroup

/-- The transported `CommGroup` on form classes of discriminant -20.
`formClassCommGroup` is a `def` (not an `instance`), so we make it a local
instance via `letI`. -/
example : CommGroup (FormClass (fieldDiscriminant (-5 : ℤ))) :=
  formClassCommGroup (by decide : (-5 : ℤ) < 0)

/-- Identity in the transported form class group maps to identity in the ideal
class group via the Cox equivalence. -/
example :
    letI := formClassCommGroup (by decide : (-5 : ℤ) < 0)
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0)
      (1 : FormClass (fieldDiscriminant (-5 : ℤ))) =
      (1 : ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) := by
  simpa [formClassCommGroup, Equiv.one_def] using
    Equiv.apply_symm_apply
      (formClassEquivClassGroup (by decide : (-5 : ℤ) < 0)) (1 : ClassGroup _)

/-- Multiplication commutes with the Cox equivalence.  The transported group
law makes the Cox map a homomorphism by construction. -/
example (x y : FormClass (fieldDiscriminant (-5 : ℤ))) :
    letI := formClassCommGroup (by decide : (-5 : ℤ) < 0)
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0) (x * y) =
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0) x *
    formClassEquivClassGroup (by decide : (-5 : ℤ) < 0) y :=
  formClassEquivClassGroup_mul (by decide : (-5 : ℤ) < 0) x y

end FormClassGroup

/-! ## 5. Cox equivalence: cardinality -/

section CoxEquivalence

/-- The Cox equivalence is a bijection, so the form class set and the ideal
class group have the same cardinality. -/
example : Fintype.card (FormClass (fieldDiscriminant (-5 : ℤ))) =
    Fintype.card (ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) := by
  classical
  exact Fintype.card_congr (formClassEquivClassGroup (by decide : (-5 : ℤ) < 0))

/-- `classP` is the non-identity element of the ideal class group.
The Cox equivalence guarantees a corresponding non-identity form class. -/
example : classP ≠ (1 : ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) :=
  classP_ne_one

end CoxEquivalence

/-! ## 6. Group law: `classP² = 1` (the group is `ℤ/2ℤ`) -/

section GroupLaw

/-- Every element of the ideal class group of `ℚ(√-5)` is either `1` or
`classP`. -/
example (C : ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) : C = 1 ∨ C = classP :=
  classGroup_eq_one_or_classP C

/-- The non-identity element `classP` is self-inverse: `classP² = 1`.
Combined with `classGroup_eq_one_or_classP`, this proves the class group
of `ℚ(√-5)` is cyclic of order 2. -/
theorem classP_mul_self_eq_one :
    classP * classP = (1 : ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ)))) := by
  have h := classGroup_eq_one_or_classP (classP * classP)
  rcases h with (h1 | hP)
  · exact h1
  · -- classP * classP = classP → cancel classP → classP = 1, contradiction
    have hclassP_eq_one : classP = 1 := by
      calc
        classP = (classP * classP) * classP⁻¹ := by simp
        _ = classP * classP⁻¹ := by rw [hP]
        _ = 1 := by simp
    exact absurd hclassP_eq_one classP_ne_one

/-- The ideal class group of `ℚ(√-5)` is cyclic of order two. -/
noncomputable def classGroupMulEquivZMod2 :
    ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ))) ≃* Multiplicative (ZMod 2) :=
  mulEquivOfPrimeCardEq (p := 2)
    (G := ClassGroup (𝓞 (Qsqrtd ((-5 : ℤ) : ℚ))))
    (G' := Multiplicative (ZMod 2))
    (by
      rw [Nat.card_eq_fintype_card]
      simpa [O, NumberField.classNumber] using classNumber_eq_two)
    (by
      rw [Nat.card_eq_fintype_card]
      simp)

end GroupLaw

end SqrtNeg5
end Examples
end QuadraticNumberFields
