/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Product Homomorphisms from `ZMod` Vectors

Small lemmas for `Multiplicative.ofAdd`, and a product homomorphism whose
exponents are `ZMod`-valued functions.
-/

open scoped BigOperators

namespace Multiplicative

section OfAdd

variable {α ι : Type*} [Zero α]

/-- A nonzero additive element remains nontrivial when viewed multiplicatively. -/
theorem ofAdd_ne_one_of_ne_zero {a : α} (ha : a ≠ 0) :
    ofAdd a ≠ 1 := by
  intro h
  exact ha (by simpa using congrArg toAdd h)

/-- A function with a nonzero coordinate remains nontrivial when viewed
multiplicatively. -/
theorem ofAdd_ne_one_of_apply_ne_zero (v : ι → α) {i : ι} (hi : v i ≠ 0) :
    ofAdd v ≠ 1 :=
  ofAdd_ne_one_of_ne_zero (by
    intro hv
    exact hi (by simp [hv]))

/-- A function with some nonzero coordinate remains nontrivial when viewed
multiplicatively. -/
theorem ofAdd_ne_one_of_exists_apply_ne_zero (v : ι → α) (hv : ∃ i, v i ≠ 0) :
    ofAdd v ≠ 1 := by
  rcases hv with ⟨i, hi⟩
  exact ofAdd_ne_one_of_apply_ne_zero v hi

end OfAdd

end Multiplicative

namespace MonoidHom

section ZModPiPow

variable {ι M : Type*} [Fintype ι] [CommGroup M]

/-- The homomorphism generated by an indexed family of `n`-torsion elements.

It sends a vector `v : ι → ZMod n` to `∏ i, g i ^ (v i).val`. -/
noncomputable def zmodPiPowHom
    (n : ℕ) [NeZero n] (g : ι → M) (hg : ∀ i, g i ^ n = 1) :
    Multiplicative (ι → ZMod n) →* M where
  toFun v := Finset.univ.prod fun i ↦ g i ^ ((Multiplicative.toAdd v i).val)
  map_one' := by
    simp
  map_mul' v w := by
    classical
    rw [← Finset.prod_mul_distrib]
    refine Finset.prod_congr rfl ?_
    intro i _hi
    rw [← pow_add]
    rw [toAdd_mul]
    simp only [Pi.add_apply]
    have hmod := ZMod.val_add (Multiplicative.toAdd v i) (Multiplicative.toAdd w i)
    have hpow_mod :
        g i ^ (((Multiplicative.toAdd v i).val + (Multiplicative.toAdd w i).val) % n) =
          g i ^ ((Multiplicative.toAdd v i).val + (Multiplicative.toAdd w i).val) := by
      exact (pow_eq_pow_mod _ (hg i)).symm
    rw [hmod, hpow_mod]

@[simp]
theorem zmodPiPowHom_apply
    (n : ℕ) [NeZero n] (g : ι → M) (hg : ∀ i, g i ^ n = 1)
    (v : ι → ZMod n) :
    zmodPiPowHom n g hg (Multiplicative.ofAdd v) =
      Finset.univ.prod fun i ↦ g i ^ (v i).val :=
  rfl

end ZModPiPow

end MonoidHom
