/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/

import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Product Homomorphisms from `ZMod`-Valued Vectors

Material destined for mathlib.
-/

open scoped BigOperators

namespace MonoidHom

section ZModPiPow

variable {ι M : Type*} [Fintype ι] [CommGroup M]

/-- The homomorphism generated by an indexed family of `n`-torsion elements.

It sends a vector `v : ι → ZMod n` to `∏ i, g i ^ (v i).val`. -/
noncomputable def zmodPiPowHom
    (n : ℕ) [NeZero n] (g : ι → M) (hg : ∀ i, g i ^ n = 1) :
    Multiplicative (ι → ZMod n) →* M where
  toFun v := Finset.univ.prod fun i ↦ g i ^ ((Multiplicative.toAdd v i).val)
  map_one' := by
    simp
  map_mul' v w := by
    classical
    rw [← Finset.prod_mul_distrib]
    refine Finset.prod_congr rfl ?_
    intro i _hi
    rw [← pow_add]
    rw [toAdd_mul]
    simp only [Pi.add_apply]
    have hmod := ZMod.val_add (Multiplicative.toAdd v i) (Multiplicative.toAdd w i)
    have hpow_mod :
        g i ^ (((Multiplicative.toAdd v i).val + (Multiplicative.toAdd w i).val) % n) =
          g i ^ ((Multiplicative.toAdd v i).val + (Multiplicative.toAdd w i).val) := by
      exact (pow_eq_pow_mod _ (hg i)).symm
    rw [hmod, hpow_mod]

@[simp]
theorem zmodPiPowHom_apply
    (n : ℕ) [NeZero n] (g : ι → M) (hg : ∀ i, g i ^ n = 1)
    (v : ι → ZMod n) :
    zmodPiPowHom n g hg (Multiplicative.ofAdd v) =
      Finset.univ.prod fun i ↦ g i ^ (v i).val :=
  rfl

end ZModPiPow

end MonoidHom
