/-
Copyright (c) 2026 Frankie Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frankie Wang
-/
import QuadraticNumberFields.RingOfIntegers.Classification
import Mathlib.Algebra.Polynomial.Degree.IsMonicOfDegree
import Mathlib.NumberTheory.NumberField.Ideal.KummerDedekind

/-!
# Monogenicity of the Ring of Integers

This file establishes that `𝓞(ℚ(√d)) = ℤ[θ]` for an explicit generator `θ`,
so that the Kummer–Dedekind theorem applies to **all** primes unconditionally.

## Main Results

* `adjoin_omega_eq_top`: In any `QuadraticAlgebra ℤ a b`, the omega element
  generates the whole ring as a ℤ-algebra.
* `adjoin_eq_top_of_ringEquiv`: Transport of monogenicity through ring equivalences.
* `ringOfIntegersGenerator`: The generator `θ` of `𝓞(ℚ(√d))` as a ℤ-algebra.
* `adjoin_generator_eq_top`: `Algebra.adjoin ℤ {θ} = ⊤`
* `exponent_generator_eq_one`: `RingOfIntegers.exponent θ = 1`

## Strategy

The ring `QuadraticAlgebra ℤ a b` is generated by `omega = ⟨0, 1⟩` as a ℤ-algebra,
since every element `⟨x, y⟩ = algebraMap x + y • omega`. This applies to both:
- `Zsqrtd d = QuadraticAlgebra ℤ d 0` (case `d % 4 ≠ 1`)
- `ZOnePlusSqrtOverTwo k = QuadraticAlgebra ℤ k 1` (case `d % 4 = 1`)

The ring equivs from `Classification.lean` transport this to `𝓞(ℚ(√d))`.
-/

open scoped NumberField

namespace QuadraticNumberFields

/-! ## Adjoin lemma for `QuadraticAlgebra` -/

/-- In any `QuadraticAlgebra ℤ a b`, the omega element generates the whole ring as a ℤ-algebra.
This is because every element `⟨x, y⟩ = algebraMap x + y • omega`. -/
theorem adjoin_omega_eq_top (a b : ℤ) :
    Algebra.adjoin ℤ ({QuadraticAlgebra.omega (a := a) (b := b)} : Set (QuadraticAlgebra ℤ a b)) =
      ⊤ := by
  rw [eq_top_iff]
  intro z _
  set S := Algebra.adjoin ℤ ({QuadraticAlgebra.omega (a := a) (b := b)} :
    Set (QuadraticAlgebra ℤ a b))
  have hω : QuadraticAlgebra.omega ∈ S := Algebra.subset_adjoin rfl
  have hre : algebraMap ℤ (QuadraticAlgebra ℤ a b) z.re ∈ S := Subalgebra.algebraMap_mem S z.re
  have him : z.im • QuadraticAlgebra.omega ∈ S := Subalgebra.smul_mem S hω z.im
  have heq : z = algebraMap ℤ _ z.re + z.im • QuadraticAlgebra.omega := by
    rw [← QuadraticAlgebra.mk_eq_add_smul_omega]
  rw [heq]
  exact add_mem hre him

/-! ## Transport through ring equivalences -/

/-- If `x` generates `B` as a ℤ-algebra and `e : A ≃+* B` is a ring equiv, then
`e.symm x` generates `A` as a ℤ-algebra. -/
theorem adjoin_eq_top_of_ringEquiv {A B : Type*} [CommRing A] [CommRing B]
    (e : A ≃+* B) (x : B) (h : Algebra.adjoin ℤ ({x} : Set B) = ⊤) :
    Algebra.adjoin ℤ ({e.symm x} : Set A) = ⊤ := by
  let e' : A ≃ₐ[ℤ] B := AlgEquiv.ofRingEquiv (f := e) (fun _ => by simp)
  have he_symm : (e'.symm x : A) = e.symm x := rfl
  have key : Subalgebra.map e'.toAlgHom (Algebra.adjoin ℤ ({e'.symm x} : Set A)) =
      Algebra.adjoin ℤ ({x} : Set B) := by
    rw [AlgHom.map_adjoin_singleton]
    congr 1
    simp [e']
  rw [← he_symm, eq_top_iff]
  intro a _
  have hmem : e' a ∈ Subalgebra.map e'.toAlgHom (Algebra.adjoin ℤ ({e'.symm x} : Set A)) := by
    rw [key, h]
    exact Algebra.mem_top
  obtain ⟨b, hb, heb⟩ := Subalgebra.mem_map.mp hmem
  rwa [show b = a from e'.injective heb] at hb

private theorem minpoly_eq_of_ringEquiv {A B : Type*} [CommRing A] [CommRing B]
    (e : A ≃+* B) (x : B) :
    minpoly ℤ (e.symm x) = minpoly ℤ x := by
  let e' : A ≃ₐ[ℤ] B := AlgEquiv.ofRingEquiv (f := e) (fun _ => by simp)
  have he_symm : (e'.symm x : A) = e.symm x := rfl
  rw [← he_symm]
  exact minpoly.algEquiv_eq e'.symm x

/-! ## The generator -/

namespace Splitting

variable (d : ℤ) [Fact (Squarefree d)] [Fact (d ≠ 1)]

/-- The generator `θ` of `𝓞(ℚ(√d))` as a ℤ-algebra.
When `d % 4 ≠ 1`, this is the image of `√d` (= `omega` in `Zsqrtd d`).
When `d % 4 = 1`, this is the image of `(1 + √d)/2` (= `omega` in `ZOnePlusSqrtOverTwo k`). -/
noncomputable def ringOfIntegersGenerator :
    𝓞 (Qsqrtd (d : ℚ)) :=
  if hd4 : d % 4 = 1 then
    let ex := RingOfIntegers.ringOfIntegers_equiv_zOnePlusSqrtOverTwo_of_mod_four_eq_one d hd4
    ex.snd.snd.symm QuadraticAlgebra.omega
  else
    (RingOfIntegers.ringOfIntegers_equiv_zsqrtd_of_mod_four_ne_one d hd4).symm
      QuadraticAlgebra.omega

/-- The generator `θ` generates `𝓞(ℚ(√d))` as a ℤ-algebra. -/
theorem adjoin_generator_eq_top :
    Algebra.adjoin ℤ ({ringOfIntegersGenerator d} : Set (𝓞 (Qsqrtd (d : ℚ)))) = ⊤ := by
  unfold ringOfIntegersGenerator
  split
  · next hd4 =>
    let ex := RingOfIntegers.ringOfIntegers_equiv_zOnePlusSqrtOverTwo_of_mod_four_eq_one d hd4
    exact adjoin_eq_top_of_ringEquiv ex.snd.snd QuadraticAlgebra.omega
      (adjoin_omega_eq_top ex.fst 1)
  · next hd4 =>
    exact adjoin_eq_top_of_ringEquiv
      (RingOfIntegers.ringOfIntegers_equiv_zsqrtd_of_mod_four_ne_one d hd4)
      QuadraticAlgebra.omega (adjoin_omega_eq_top d 0)

/-- The exponent of the generator is `1`, i.e., `𝓞 = ℤ[θ]` exactly. -/
theorem exponent_generator_eq_one :
    RingOfIntegers.exponent (ringOfIntegersGenerator d) = 1 :=
  RingOfIntegers.exponent_eq_one_iff.mpr (adjoin_generator_eq_top d)

/-- Kummer–Dedekind applies unconditionally: no prime divides the exponent. -/
theorem not_dvd_exponent_generator (p : ℕ) [Fact p.Prime] :
    ¬ p ∣ RingOfIntegers.exponent (ringOfIntegersGenerator d) := by
  rw [exponent_generator_eq_one]
  intro h
  have := Nat.le_of_dvd Nat.one_pos h
  have := (Fact.out : Nat.Prime p).one_lt
  omega

/-! ## Minimal polynomial computation -/

open Polynomial in
/-- In `QuadraticAlgebra ℤ a 0`, `omega` satisfies `X² - a`. -/
theorem aeval_omega_X_sq_sub_C (a : ℤ) :
    (Polynomial.aeval (QuadraticAlgebra.omega (R := ℤ) (a := a) (b := 0)))
      (X ^ 2 - C a) = 0 := by
  simp only [eq_intCast, aeval_sub, map_pow, aeval_X, map_intCast]
  rw [sq, QuadraticAlgebra.omega_mul_omega_eq_mk]
  ext <;> simp

open Polynomial in
/-- In `QuadraticAlgebra ℤ k 1`, `omega` satisfies `X² - X - k`. -/
theorem aeval_omega_X_sq_sub_X_sub_C (k : ℤ) :
    (Polynomial.aeval (QuadraticAlgebra.omega (R := ℤ) (a := k) (b := 1)))
      (X ^ 2 - X - C k) = 0 := by
  simp only [eq_intCast, aeval_sub, map_pow, aeval_X, map_intCast]
  rw [sq, QuadraticAlgebra.omega_mul_omega_eq_mk]
  ext <;> simp

open Polynomial in
/-- `omega` in `QuadraticAlgebra ℤ a b` is not in the image of `algebraMap ℤ`. -/
theorem omega_ne_algebraMap (a b : ℤ) (c : ℤ) :
    (QuadraticAlgebra.omega (R := ℤ) (a := a) (b := b)) ≠ algebraMap ℤ _ c := by
  intro h
  have := congr_arg QuadraticAlgebra.im h
  simp [QuadraticAlgebra.omega] at this

open Polynomial in
private lemma eq_C_add_C_mul_X_of_natDegree_lt_two {q : ℤ[X]} (hq : q.natDegree < 2) :
    q = C (q.coeff 0) + C (q.coeff 1) * X := by
  calc
    q = ∑ i ∈ Finset.range 2, C (q.coeff i) * X ^ i := by
      simpa using q.as_sum_range_C_mul_X_pow' hq
    _ = C (q.coeff 0) + C (q.coeff 1) * X := by
      norm_num [Finset.sum_range_succ]

open Polynomial in
private lemma eq_zero_of_aeval_omega_eq_zero_of_natDegree_lt_two (a b : ℤ) {q : ℤ[X]}
    (hq : q.natDegree < 2)
    (hroot : Polynomial.aeval (QuadraticAlgebra.omega (R := ℤ) (a := a) (b := b)) q = 0) :
    q = 0 := by
  have hqform := eq_C_add_C_mul_X_of_natDegree_lt_two hq
  rw [hqform] at hroot ⊢
  have hre := congr_arg QuadraticAlgebra.re hroot
  have him := congr_arg QuadraticAlgebra.im hroot
  simp at hre him
  simp [hre, him]

open Polynomial in
private lemma natDegree_lt_two_of_degree_lt {q p : ℤ[X]} (hqzero : q ≠ 0)
    (hp : p.degree = 2) (hq : q.degree < p.degree) :
    q.natDegree < 2 := by
  rw [hp, degree_eq_natDegree hqzero] at hq
  exact WithBot.coe_lt_coe.mp hq

open Polynomial in
/-- The minimal polynomial of `omega` in `QuadraticAlgebra ℤ d 0` is `X² - d`. -/
theorem minpoly_omega_quadAlg_zero (d : ℤ) :
    minpoly ℤ (QuadraticAlgebra.omega (R := ℤ) (a := d) (b := 0)) = X ^ 2 - C d := by
  symm
  refine minpoly.unique' ℤ (QuadraticAlgebra.omega (R := ℤ) (a := d) (b := 0))
    (monic_X_pow_sub_C d two_ne_zero) (aeval_omega_X_sq_sub_C d) ?_
  intro q hq
  by_cases hqzero : q = 0
  · exact Or.inl hqzero
  · right
    intro hroot
    apply hqzero
    exact eq_zero_of_aeval_omega_eq_zero_of_natDegree_lt_two d 0
      (natDegree_lt_two_of_degree_lt hqzero (degree_X_pow_sub_C zero_lt_two d) hq) hroot

open Polynomial in
/-- The minimal polynomial of `omega` in `QuadraticAlgebra ℤ k 1` is `X² - X - k`. -/
theorem minpoly_omega_quadAlg_one (k : ℤ) :
    minpoly ℤ (QuadraticAlgebra.omega (R := ℤ) (a := k) (b := 1)) = X ^ 2 - X - C k := by
  symm
  have hmd : Polynomial.IsMonicOfDegree (X ^ 2 - X - C k : ℤ[X]) 2 := by
    simpa [sub_eq_add_neg, one_mul] using
      (Polynomial.isMonicOfDegree_sub_add_two (R := ℤ) (1 : ℤ) (-k))
  refine minpoly.unique' ℤ (QuadraticAlgebra.omega (R := ℤ) (a := k) (b := 1)) hmd.monic
    (aeval_omega_X_sq_sub_X_sub_C k) ?_
  intro q hq
  by_cases hqzero : q = 0
  · exact Or.inl hqzero
  · right
    intro hroot
    apply hqzero
    have hpdeg : (X ^ 2 - X - C k : ℤ[X]).degree = 2 := by
      rw [degree_eq_natDegree hmd.monic.ne_zero, hmd.natDegree_eq]
      rfl
    exact eq_zero_of_aeval_omega_eq_zero_of_natDegree_lt_two k 1
      (natDegree_lt_two_of_degree_lt hqzero hpdeg hq) hroot

/-- The minimal polynomial of the generator `θ` of `𝓞(ℚ(√d))`.
When `d % 4 ≠ 1`: `minpoly ℤ θ = X² - d`.
When `d % 4 = 1` (with `d = 1 + 4k`): `minpoly ℤ θ = X² - X - k`. -/
theorem minpoly_generator :
    (d % 4 ≠ 1 → minpoly ℤ (ringOfIntegersGenerator d) = Polynomial.X ^ 2 - Polynomial.C d) ∧
    (∀ hd4 : d % 4 = 1,
      let ex := RingOfIntegers.ringOfIntegers_equiv_zOnePlusSqrtOverTwo_of_mod_four_eq_one d hd4
      minpoly ℤ (ringOfIntegersGenerator d) =
        Polynomial.X ^ 2 - Polynomial.X - Polynomial.C ex.fst) := by
  constructor
  · intro hd4
    unfold ringOfIntegersGenerator
    rw [dif_neg hd4]
    calc
      minpoly ℤ ((RingOfIntegers.ringOfIntegers_equiv_zsqrtd_of_mod_four_ne_one d hd4).symm
          QuadraticAlgebra.omega) =
          minpoly ℤ (QuadraticAlgebra.omega (R := ℤ) (a := d) (b := 0)) :=
        minpoly_eq_of_ringEquiv
          (RingOfIntegers.ringOfIntegers_equiv_zsqrtd_of_mod_four_ne_one d hd4)
          QuadraticAlgebra.omega
      _ = Polynomial.X ^ 2 - Polynomial.C d := minpoly_omega_quadAlg_zero d
  · intro hd4
    unfold ringOfIntegersGenerator
    rw [dif_pos hd4]
    let ex := RingOfIntegers.ringOfIntegers_equiv_zOnePlusSqrtOverTwo_of_mod_four_eq_one d hd4
    calc
      minpoly ℤ (ex.snd.snd.symm QuadraticAlgebra.omega) =
          minpoly ℤ (QuadraticAlgebra.omega (R := ℤ) (a := ex.fst) (b := 1)) :=
        minpoly_eq_of_ringEquiv ex.snd.snd QuadraticAlgebra.omega
      _ = Polynomial.X ^ 2 - Polynomial.X - Polynomial.C ex.fst :=
        minpoly_omega_quadAlg_one ex.fst

end Splitting
end QuadraticNumberFields
